### ISSUE TITLE
Convert script?

### ISSUE THREAD

**Issue by jbenet** [asciinema/asciinema-player#10]
I found https://gist.github.com/sickill/504474702dd18c7dc0ec -- is this still needed? if so, would be nice to make a version that's easier to run (ideally something we can `npm install` and have work reproducibly. (the script calls for installing a bunch of libs for compiling `libtsm`).

**Comment by sickill** [comment]
This is still needed atm, but one of high priority tasks is implementing interpretation of the original (recorded) JSON format directly in the player, so this step won't be necessary. I don't have ETA for this but it will happen.

**Comment by sickill** [comment]
Here's a simple script that fetches the converted asciicast from asciinema.org, given the URL of the asciicast page and output filename: https://gist.github.com/sickill/3b12136b727e0f3163dc

Given that asciicasts on asciinema.org are private by default this may be reasonable, temporary solution.

**Comment by jbenet** [comment]
thanks -- will publish a node pkg to do this easily for users.

**Comment by sickill** [comment]
@jbenet look at the README now, the player now (v2.0.0 just released) directly supports asciicast v1 format, without a need for any convert script.

**Comment by sickill** [comment]
Btw, I plan to add support for playback from `ipfs://` URLs - it will automatically rewrite them to use the ipfs.io gateway (similar to cli which already supports that).
