### ISSUE TITLE
Some unicode symbols are wider than others (which results to inconsistent views)

### ISSUE THREAD

**Issue by chshersh** [asciinema/asciinema-player#100]
Consider the following demo:

* https://asciinema.org/a/214424

This unicode symbol is used: ⓘ

And because of that some borders are aligned weirdly. Everything works fine locally :+1:

**Comment by sickill** [comment]
Yup, this is related to missing wide-character support (#34).

**Comment by ku1ik** [comment]
The recently released 3.7.1 version of the player got several improvements around rendering accuracy, mostly fixing positioning and alignment of various character groups (ascii drawing, block elements, Powerline symbols, CJK, emoji). It should look much better than before now.

The linked demo looks good to me now:

[![asciicast](https://asciinema.org/a/214424.svg)](https://asciinema.org/a/214424)

The ⓘ symbol still makes the following text slightly shifted but it doesn't cause problems with alignment of the borders anymore.

Do you think this looks good enough?

**Comment by chshersh** [comment]
Thank you, @ku1ik! That looks great 💯
