### ISSUE TITLE
Split-screen or sync-ing two players

### ISSUE THREAD

**Issue by iam-TJ** [asciinema/asciinema-player#104]
Is there a way to play back 2 (or more) casts in sync with each other, either in separate player instances or split-screen (vertical or horizontal) in one player instance?

I'm thinking it'd need some kind of absolute timestamp at the start of the casts to ensure synchronisation (due to it being difficult to trigger recordings at the same moment).
 
I'm wanting to demonstrate 'cause' and 'effect'.

Scenario 1: client HTTP requests, server 'tail -f' on log file
Scenario 2: commands in a hypervisor monitor console, reaction in the virtual machine guest
Scenario 3: debugger console, executing application

**Comment by sickill** [comment]
There's no support for synchronizing multiple player instances together unfortunatelly.
Fortunatelly, what @mathieu-aubin suggested should work well for your use case (assuming you are or can get familiar with tmux), and is what people have been doing.

**Comment by mathieu-aubin** [comment]
wouldnt it be possible somehow to script a record of each seperate panes with a tmux/asciinema ninjafoo command?

im sure it can be done, even if it means introducing some external evils.

tmuxifier (or very close spelling) is what i think about when referring to evils

let us/me know about your findings if you value your input to the community - i should quit opiates. ah.

**Comment by mathieu-aubin** [comment]
@sickill how bad/hard would it be to introduce a gmt timestamp to a v2 cast withouth breaking the bank on devel and testing?

also, unrelated, did you ever think of making the format a little more « official » by adding some file/magic to the .cast ext format?

**Comment by sickill** [comment]
@mathieu-aubin we do have a timestamp of the beginning of recording in v2: https://github.com/asciinema/asciinema/blob/develop/doc/asciicast-v2.md#timestamp

What do you mean by "file/magic"?

**Comment by iam-TJ** [comment]
By file-magic I assume the suggestion is a static, recognisable signature in the first few octets that tools like file (1), etc., can use via magic (5) which could also be a shebang style line as used by binfmt.

**Comment by sickill** [comment]
The file/magic bit could be nice, but I'm not sure how to add it in a backwards compatible way.

Anyway, since we kind of "solved" the split-screen issue I'm going to close it now.
Feel free to open a separate issue for file/magic if you have any suggestions.
