### ISSUE TITLE
start-at attribute only supports integer seconds.

### ISSUE THREAD

**Issue by camlspotter** [asciinema/asciinema-player#105]
I use `asciinema-player` v2.6.1 https://github.com/asciinema/asciinema-player/releases/tag/v2.6.1 , and found that `start-at` attribute only support integer values:

* `start-at=10` works fine.
* `start-at="10.4"` is treated as `start-at=10`
* `start-at="0:10"` seems to be completely ignored.  Same for `start-at="0:10.5"`.

It should be great if `start-at` supports the same granularity as `poster` attribute, where we can write 
 `poster="npt:0:10.2"`.

**Comment by sickill** [comment]
This has been fixed in v3. See https://github.com/asciinema/asciinema-player#startat (it doesn't mention fractions of a second but it works).
