### ISSUE TITLE
Can the player trigger an event whenever the user submits a command in a shell recording?

### ISSUE THREAD

**Issue by layoutanalysis** [asciinema/asciinema-player#106]
Yesterday I did a small mashup prototype called Shell Souffleur: https://layoutanalysis.github.io/shell-souffleur/index.html

It takes an asciinema recording and calls explainshell.com for every shell command submitted in the recording. Unfortunately, Shell Souffleur is all smoke-and-mirrors right now, because the asciinema player doesn't trigger events for actions in the recording (e.g. command submitted, output received).

Can this be changed or is there a good workaround (e.g. parsing the cast file on my own) ?

**Comment by sickill** [comment]
asciinema doesn't record on the shell level, it does record on terminal level, and there's subtle difference between them. So asciinema is able to see the stream of all input and output characters flowing into and out of terminal, but a shell, like bash, is opaque to asciinema. 

Anyway, the best you can do is to parse the cast file. It may be helpful to record with input (`--stdin` flag), which will include `i` events in the output cast file, and these will only have text that was entered by you, while `o` has text that is actually printed.
