### ISSUE TITLE
Feature request for a start-at list of time sequences 

### ISSUE THREAD

**Issue by typelogic** [asciinema/asciinema-player#108]
Instead of only 1 start-at, requesting instead to have a list of these time sequences instead so that i could skip unwanted portions and emphasize important ones. Command-line sessions have dull gaps in them while we grope on certain things. There are actually only few bright moments we like to emphasize during a session replay. A nice in-between visual indicator to let know we are now jumping to the next sequence, or whatever is most presentable to the viewer.

**Comment by sickill** [comment]
There's upcoming "breakpoints" feature which could be used for this use case I believe. See https://github.com/asciinema/asciinema/pull/341 It's not finished yet though. The PR adds breakpoints to the asciicast format and ability to add a breakpoint during recording session. We'll still need to add support for this in the player.

**Comment by sickill** [comment]
Given above we won't modify the behavior of start-at and most likely utilize breakpoints (when it's ready) for such use case.
