### ISSUE TITLE
grunt-cli ?

### ISSUE THREAD

**Issue by jbenet** [asciinema/asciinema-player#11]
i think this needs grunt-cli? else `node_modules/.bin/grunt` is not there.

**Comment by sickill** [comment]
That's true, I guess this information is missing from the README file. 

On a related note, development happens now in `next` branch (https://github.com/asciinema/asciinema-player/tree/next). It's ClojureScript + leiningen, so building is different there (no grunt and other node tools).

**Comment by sickill** [comment]
Closing as this doesn't apply anymore.
