### ISSUE TITLE
QUESTION: I want to contribute this project but I'm not familiar with ClojureScript. Is there any plan to use pure JavaScript/TypeScript?

### ISSUE THREAD

**Issue by JavaCS3** [asciinema/asciinema-player#112]

**Comment by jiangts** [comment]
what a perfect opportunity to learn ClojureScript! :)

**Comment by JavaCS3** [comment]
> what a perfect opportunity to learn ClojureScript! :)

I don't want to spend too much time on learning a new language because what ClousreScript is doing is generating JavaScript but I know how to write JavaScript already.

**Comment by sickill** [comment]
The latest version of the player has been [rewritten in JS+Rust](https://blog.asciinema.org/post/smaller-faster/).
