### ISSUE TITLE
Symbols misaligned in zsh recording

### ISSUE THREAD

**Issue by JonZeolla** [asciinema/asciinema-player#118]
It seems that my symbols from zsh (powerlevel9k theme using [Source Code Pro for Powerline](https://github.com/powerline/fonts/blob/master/SourceCodePro/Source%20Code%20Pro%20for%20Powerline.otf)) are being misaligned in my recordings, both locally and when uploaded to a [public asciinema.org recording](https://asciinema.org/a/270899).  Here is how it looks locally in my iTerm 2:

<img width="1665" alt="Screen Shot 2019-09-25 at 9 58 00 AM" src="https://user-images.githubusercontent.com/1385510/65607775-12269280-df7b-11e9-84fd-2531f40a7272.png">

I also used the `asciinema/asciicast2gif` docker container to convert my cast to a gif and the result was the same in the gif.

In looking more closely at #84 it seems that this issue existed there as well.  I'm not a css expert but I spent a few hours trying to get things to line up well without botching the rest of the prompts without success.

**Comment by sickill** [comment]
Do you still see the misalignment here https://asciinema.org/a/270899 ? 

This is how it renders for me under Firefox:

<img width="926" alt="Zrzut ekranu 2021-12-11 o 18 25 31" src="https://user-images.githubusercontent.com/17589/145685809-f85c2ffb-2667-4b1a-8d56-c5c888adbb5d.png">

Looks alright to me.

**Comment by JonZeolla** [comment]
Yes I see it in your example and just now for me in chrome on my Android phone.
![Screenshot_20211211-130138](https://user-images.githubusercontent.com/1385510/145686920-d63711c3-3e43-4023-919c-fa7ed2a3000b.png)

**Comment by sickill** [comment]
I see. That's going to be hard to fix with the current rendered as it relies on browser's text rendering capabilities, and there are some inconsistencies between browsers and OSes. The only reliable way to fix this would be to create a canvas based rendered, where we'd have much greater control on positioning things.

**Comment by JonZeolla** [comment]
Great work! Just updated my project. Thanks
