### ISSUE TITLE
When can I support vue.js

### ISSUE THREAD

**Issue by Ilovedocker** [asciinema/asciinema-player#119]
When can I support vue.js

**Comment by poseidonphp** [comment]
Bump. 
I got a working vue component to play a file from a self-hosted location. However, when using single page applications, the video loads when the page is refreshed (even works with multiple players on the page). But if you navigate to another page that has a video, subsequent videos do not load. 
There appears to be some binding issue with the way the custom asciinema-player component is created. If I try to play the video, it doesn’t load the source file (watching the network tab). 
It would be nice to have a vue component that initializes and destroys the player object; self-contained within the component.

**Comment by poseidonphp** [comment]
Other possible alternative: Could this be made similar to other JS packages where it exposes a variable/method that can be bound to an element?
Example would be the Select2 package:
```
$(document).ready(function() {
    $('#my-select-menu').select2();
});
```
This would allow developers to attach the player to a div, without generating any custom html elements.

**Comment by chengongliang** [comment]
> Bump.
> I got a working vue component to play a file from a self-hosted location. However, when using single page applications, the video loads when the page is refreshed (even works with multiple players on the page). But if you navigate to another page that has a video, subsequent videos do not load.
> There appears to be some binding issue with the way the custom asciinema-player component is created. If I try to play the video, it doesn’t load the source file (watching the network tab).
> It would be nice to have a vue component that initializes and destroys the player object; self-contained within the component.

Could you share your component?

**Comment by xiaowang04821** [comment]
Do you have any plans to use on vue.js, thank you.

**Comment by sickill** [comment]
The new version of the player was released to npmjs.org (currently at 3.0.0-rc.1), which provides a proper ES module to be used in your own apps, and it can also be used as an external, standalone script. 

You should be able to use it now with any JS view library (Vue.js, React.js, ...) as well as without one. asciinema project doesn't provide wrapper libs for Vue/React at the moment (not planned) but it would probably take a couple of lines of code to wrap it in a component.

See the updated self-hosting quick-start guide: https://github.com/asciinema/asciinema-player#quick-start
