### ISSUE TITLE
uncaught exception: only asciicast v1 and v2 formats can be opened

### ISSUE THREAD

**Issue by coderkan** [asciinema/asciinema-player#120]
Hi everyone,

I try to use asciinema-player but I have some trouble. I have installed the latest version of asciinema-player and implemented as it's installation README.md file. I am developing in Angular2+ this project. The asciinema-player code like below.

```javascript
<div class="p-col-12 p-md-6">
    <asciinema-player style="width: 100%; height: 100%;" src="https://asciinema.org/a/234381"</asciinema-player>
</div>
```

When I click to play button in asciinema-player, I gave an error like below.
I have tried **https://asciinema.org/a/234381.cast**, **https://asciinema.org/a/234381.json** 's file extensions and there are no reason. I encountered `uncaught exception: only asciicast v1 and v2 formats can be opened` error.

Has any idea about this problem?

![image](https://user-images.githubusercontent.com/8382599/68294250-c0f0df00-00a0-11ea-95b8-1718a603e891.png)

Regards.
Erkan

**Comment by mathieu-aubin** [comment]
Go to https://asciinema.org/docs/embedding

Should be a <script> block.

**Comment by coderkan** [comment]
Hi @mathieu-aubin,

Thanks for your reply. I have worked on this issue. I got the solution like below.
I am using Angular8 in my project. If I write  `<script src="https://asciinema.org/a/234381.js" id="asciicast-234381" async data-autoplay="true" data-size="big"></script>`  in the **index.html**, it works well. But if I want to use it in the component, I got problems. Because it seems like script injections. 

I tried the script like below.

typescript

```javascript
  scriptHtml = '<script src="https://asciinema.org/a/234381.js" id="asciicast-234381" async data-autoplay="true" data-size="big"></script>';

  constructor(private sanitizer: DomSanitizer) { }
  //<script [innerHtml]="script"></script>
  ngOnInit() {
    this.safeScript = this.sanitizer.bypassSecurityTrustHtml(this.scriptHtml); 
  }
```

html
```html
<div class="p-col-12 p-md-6" style="height: 50px;" [innerHtml]="safeScript">
</div>
```

In this scenario, there are no value to show. Nothing to do.

I have tried another way and it works well.

typescript
```javascript
  safeHtml: any;
  videoNumber: string;

  constructor(private sanitizer: DomSanitizer) {
  }
  ngOnInit() {
      this.videoNumber = '210847';
      this.safeHtml = this.sanitizer.bypassSecurityTrustHtml('<iframe allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true" src="https://asciinema.org/a/' + this.videoNumber + '/iframe"></iframe>');
   
  }
```

html
```html
  <div class="p-col-12 p-md-6">
            <div [innerHtml]="safeHtml"></div>
  </div>
```
At this time, it worked well. I tried many thing to show asciinema in <ascii-player>, but it did not worked. 

![demo](https://user-images.githubusercontent.com/8382599/69335290-a8babb80-0c6d-11ea-894c-fc8040e6512e.gif)

Regards
Erkan

**Comment by alexlai97** [comment]
I wrote a `index.html` and put the downloaded `.js`, `.css`, `asciicast.json` in the same directory.
[![asciicast](https://asciinema.org/a/9XcNjIEGw3c3xZh2sSFVezsFD.svg)](https://asciinema.org/a/9XcNjIEGw3c3xZh2sSFVezsFD)

## Results
I tried to open `index.html` in my linux firefox, 
![Imgur](https://i.imgur.com/FaRSaeT.png)

in a windows explorer,
![Imgur](https://i.imgur.com/VJAXyrf.png)

in a windows chrome,
![Imgur](https://i.imgur.com/s1Ed6z6.png)

in a windows firefox, it works !
![Imgur](https://i.imgur.com/QgsylQU.png)

Only in the windows firefox it works. (not the linux firefox :cry:)

**Comment by coderkan** [comment]
Hi @alexlai97 

I think that you should change your source from **.json** to **.cast** file extension. I have tried like below, It worked in windows, *Opera Browser, Firefox and Chrome*.  I haven't tried in Linux, yet. 

```html
<html>
<head>
  ...
  <link rel="stylesheet" type="text/css" href="./asciinema-player.css" />
  ...
</head>
<body>
  ...
  <asciinema-player src="./ascii.cast"></asciinema-player>
  ...
  <script src="./asciinema-player.js"></script>
</body>
</html>
```

Regards
Erkan

**Comment by alexlai97** [comment]
Hi, @coderkan 

The `.json` file works (only) in windows firefox for me. 
I tried the .json, .cast files, and it doesn't work for me on linux for `firefox`, `vimb`, `surf`, same error.

Should I enable CORS ? How do I do that ?

**Comment by thecalliopecrashed** [comment]
I am seeing the same error for my v2 (JSONL) asciicast file in Chrome, Firefox, and Safari on OS X.

Strangely, when I open the same file in development on `localhost:3449/element.html`, it plays fine.
The issue only occurs on the production build of asciinema-player.

**Comment by c4lliope** [comment]
Aha! Seems like my issue is more related to #72 - I was using the `<asciinema-player>` tag inside some React-rendered JSX.

I moved my tag to the static-HTML part of my page, and (still using a production build) the cast began playing, no problem.

So something is conflicting with React. I can work around this on my page for now, but down the road I may need the compatibility improved. Fingers crossed, I guess.

**Comment by liminghua999** [comment]
Hello everyone:
  `I alse meet this error too`
  `I use asciinema-player in vue page`
  `src set localhost .cast file`
  `it always report:  Uncaught only asciicast v1 and v2 formats can be opened`
**Uncaught only asciicast v1 and v2 formats can be opened**

But I set same .cast file into single html file,  it work good 
the html file is same to vue page 

why? why? why?
![image](https://user-images.githubusercontent.com/18185326/109773174-d7c62800-7c39-11eb-9d5a-b0660102cbdb.png)

![image](https://user-images.githubusercontent.com/18185326/109773105-c4b35800-7c39-11eb-81f3-4fcb55ff39ec.png)

**Comment by shly** [comment]
I also had this problem, have you solved it?@liminghua999

**Comment by sickill** [comment]
The player has been rewritten from scratch since all of the above was said so I'm going to close it. Feel free to try v3.0.

**Comment by xuehaoweng** [comment]
i  used vue3.0  and typescript  ，how to use this, i also had this problem : Uncaught only asciicast v1 and v2 formats can be opened
