### ISSUE TITLE
React: Removing and re-adding player

### ISSUE THREAD

**Issue by RocioMilla** [asciinema/asciinema-player#121]
React version:  16.11.0
Asciinema-player version: 2.6.1

When I start my app, asciinema-player works but when I remove the player from DOM and add it again it doesn't load and shows "Uncaught only asciicast v1 and v2 formats can be opened"

```
const MountTest = props => {

    const [toggle,setToggle] = useState(true);

    return<div>
        <button onClick={()=>setToggle(!toggle)}>Toggle</button>
        {toggle && <asciinema-player src="https://asciinema.org/a/153907.cast"/> }
    </div>

}

ReactDOM.render(<MountTest></MountTest>, document.getElementById('root'));
```

Any ideas? Thanks!

**Comment by artfb** [comment]
I had a similar issue. Try `<div dangerouslySetInnerHTML={{ __html: html }}></div>`

**Comment by RocioMilla** [comment]
It worked. Thanks!
