### ISSUE TITLE
nethack with curses graphics displays poorly in the web player

### ISSUE THREAD

**Issue by mihaifm** [asciinema/asciinema-player#124]
There seems to be a problem with the web player not displaying some things properly. Unfortunately I have no knowledge of how asciinema works to provide more details, however I attached the cast.

[demo cast](https://github.com/asciinema/asciinema-player/files/3963865/demo.zip)

Expected output (in the terminal, with `asciinema play`)

![Screenshot from 2019-12-14 15-14-12](https://user-images.githubusercontent.com/981184/70849294-52fcbc00-1e85-11ea-9bc1-34bb3e0ea991.png)

Actual web player output:

![Screenshot from 2019-12-14 15-15-15](https://user-images.githubusercontent.com/981184/70849302-7889c580-1e85-11ea-9325-81e085b64ed9.png)

**Comment by sickill** [comment]
Found it! It was missing support for XTerm control sequence `REP` (https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h4-Functions-using-CSI-_-ordered-by-the-final-character-lparen-s-rparen:CSI-Ps-b.1CA2).

It looks like expected now:


<img width="931" alt="Zrzut ekranu 2021-11-13 o 20 15 47" src="https://user-images.githubusercontent.com/17589/141656423-1f90522c-23dd-4cec-a3ad-6de8ab136a97.png">

The patch is in `develop` now, will be released soon with v3.0.0-beta.3.

**Comment by mihaifm** [comment]
Awesome, thanks for the great work.

**Comment by sickill** [comment]
New player with the fix has been pushed npmjs.org, and asciinema.org was updated to use it already.
