### ISSUE TITLE
ReferenceError: React is not defined

### ISSUE THREAD

**Issue by yangwawa0323** [asciinema/asciinema-player#125]
When I use in nodejs with command
**shell>** npm install asciinema-player
In my code 
```javascript
   require('asciinema-player')
   
```
It's raise an error in web console "**ReferenceError: React is not defined**"

I following the debug message goto to the asciinema-player.js at **line 60**,
before the 60th line,
```javascript
/**
 * React v15.5.4
 *
 * Copyright 2013-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 *
 */
```
The 60th line is compact javascript React v15.5.4, I have no idea to troubleshooting.

**Comment by xiaowang04821** [comment]
Yes,I also encountered this problem when I tried to use it in vue.js, and I don't know how to solve it...

**Comment by sickill** [comment]
New version of the player (3.0) doesn't use React.js anymore, and it's a proper npm package exposing ES module. It's at 3.0.0-rc1 at the moment, final version is coming soon though.
