### ISSUE TITLE
Playback start time in URL

### ISSUE THREAD

**Issue by vvv** [asciinema/asciinema-player#13]
It would be useful if asciinema player supported playback start time argument in URLs.
This would allow to refer to a particular place in an asciicast.

We could mimic YouTube format: `?t=37s`, `?t=2m10s`.
Example: open https://asciinema.org/a/23012?t=18s ==> the playback starts (immediately) from position 0:18.

Users will also be able to mark interesting parts of their asciicasts in the description, e.g.
```
Tetris in Go, written by jjinux

[0:28](https://asciinema.org/a/20946?t=28s) First row completed.
[3:50](https://asciinema.org/a/20946?t=3m50s) Nice move!
```

**Comment by sickill** [comment]
+1

**Comment by sickill** [comment]
Would it make sense to start the playback automatically in this case? I'm not a big fan of auto-play. Does YouTube auto-play when you specify starting time?

**Comment by vvv** [comment]
YouTube does start playback in case of `?t=` links.
(Paused asciinema also starts playback, once the user moves screencast to a different position.)

**Comment by sickill** [comment]
Yeah, this changed in master recently, it doesn't resume when seeking anymore.
Anyway, it is probably fine then to auto start playback (in other words force `autoPlay=true`) when starting time is specified.

**Comment by sickill** [comment]
The player supports `startAt` option now, which specifies the time (in seconds) from which to start the playback.

I'll add support for `?t=123` to asciinema.org (you can follow https://github.com/asciinema/asciinema.org/issues/142).

**Comment by vvv** [comment]
Great job, @sickill!
