### ISSUE TITLE
Reduce the final bundle size

### ISSUE THREAD

**Issue by fjorgemota** [asciinema/asciinema-player#131]
Hey!

First, thanks for the project, it seems pretty awesome and I definitely like to recommend it to anyone needing to record the terminal and sharing on the web.

Unfortunately, there's an aspect of this project that I, personally, don't like too much: [the final bundle size](https://bundlephobia.com/result?p=asciinema-player@2.6.1), which according to bundlephobia is 133.2 KB of minified+gzipped JS **just** for the player.

One of the reasons for this, I think, is the fact that this library basically embeds React minified inside the final bundle, and [React itself is quite big](https://bundlephobia.com/result?p=react-dom@16.12.0). I think there are other things that are helping yet more to reach that size.

So, given this, I would like to suggest a few possibilities to improve the situation:

a) Remove React.js dependency from the final bundle, using import or require to import the module on demand from the node_modules folder; (that would be better)
b) Use Preact (maybe with `preact/compat`) instead of React, given that it's smaller and better suited for widgets and embedded components;

This would help to reduce the final bundle size quite a bit, and would also allow to avoid conflicts with React already used in the page itself, by allowing to share dependencies code between other libraries.

What do you think? Is this possible to do?

**Comment by sickill** [comment]
The new version has been merged to mainline branch and released to npmjs.org (currently at 3.0.0-rc.1). You can read more details about the rewrite [on the blog](https://blog.asciinema.org/post/smaller-faster/).
