### ISSUE TITLE
Support nerd fonts

### ISSUE THREAD

**Issue by felipecrs** [asciinema/asciinema-player#140]
I'm not sure if this is the right place to open this feature request, but it would be awesome if the web player could support [Nerd Fonts](https://github.com/ryanoasis/nerd-fonts) which might be in use in the terminal.

See this example:
[![asciicast](https://asciinema.org/a/48w6lO2LYhm8a1lya5hPl1C0v.svg)](https://asciinema.org/a/48w6lO2LYhm8a1lya5hPl1C0v)

Unfortunately, it displays [] where it was supposed to display the glyphs.

**Comment by mplattner** [comment]
If you are self-hosting your casts, you might want to have a look at https://www.tonylykke.com/posts/2018/06/18/custom-fonts-in-asciinema/

**Comment by felipecrs** [comment]
> If you are self-hosting your casts, you might want to have a look at https://www.tonylykke.com/posts/2018/06/18/custom-fonts-in-asciinema/

Thank you so much. I'm actually requesting for the public player on `asciinema.org` to use any font which has Nerd Fonts glyphs since many people use them in their prompts and it would be harmless to support more glyphs anyway.

**Comment by mplattner** [comment]
I agree, supporting patched fonts would be great. I guess a problem is that comprehensive fonts (with font awesome etc.) are quite large, sometimes up to 1MB, and thus, significantly increase the page size. However, there could be a flag in the cast-file that indicates if a patched/custom font is needed.

**Comment by sickill** [comment]
I added new option to the player in #175 - `terminalFontFamily` - which can be used to override the default `font-family`, and therefore can be used to include Nerd Font / Font Awesome etc.

I don't think bundling NF / FA with the player makes sense, it should be rather up to you to unleash the custom font assets onto your viewers, also which flavor of the font to unleash. So I'm going to close this one, as completed.

As for Nerd Fonts on asciinema.org - there's related issue about this: https://github.com/asciinema/asciinema-server/issues/383
Player getting this new option makes a nice step forward in solving this for the website.
