### ISSUE TITLE
adjust default "keyframe" image based on start time

### ISSUE THREAD

**Issue by simonmichael** [asciinema/asciinema-player#15]
The player shows an initial image based on the first few seconds of playback, which is great. It would be even better if this could adjust appropriately when data-t or ?t= is specified.

Thanks for asciinema!

**Comment by sickill** [comment]
With `?t=` autoplay is implied so the preview is in most cases not visible (at least not for long). It would indeed make sense to do this for `data-t` in embedded player. Thanks for the idea!

**Comment by sickill** [comment]
In order to get actual terminal content at an arbitrary time the player needs to have the asciicast fetched. Preloading (#19) needs to be implemented first.

**Comment by sickill** [comment]
This was added in 0547265b8511c1d52d9a5d65b169446d93b23815 and is now running on asciinema.org.
