### ISSUE TITLE
Upload latest version to cdnjs

### ISSUE THREAD

**Issue by felbinger** [asciinema/asciinema-player#150]
The latest version of asciinema-player on https://cdnjs.com/libraries/asciinema-player is 2.4.1.
![image](https://user-images.githubusercontent.com/26925347/120897244-62e20000-c625-11eb-907a-5bbd7eb384e4.png)

Can you upload a newer version (https://github.com/asciinema/asciinema-player/releases/tag/v2.6.1), or do they have to collect the newest version from github?

**Comment by sickill** [comment]
Btw, unpkg.com seems to do the trick too:

```html
<html>
<head>
<link rel="stylesheet" type="text/css" href="https://unpkg.com/asciinema-player@3.0.0-rc.1/dist/bundle/asciinema-player.css" />
</head>
<body>
<div id="demo" class="player"></div>
<script src="https://unpkg.com/asciinema-player@3.0.0-rc.1/dist/bundle/asciinema-player.min.js"></script>
<script>
  AsciinemaPlayer.create('https://asciinema.org/a/20055.cast', document.getElementById('demo'), {
    speed: 3,
    poster: 'npt:9.5'
  });
</script>
</body>
```
