### ISSUE TITLE
Feature request: fullscreen font-size

### ISSUE THREAD

**Issue by paullaffitte** [asciinema/asciinema-player#151]
It could be nice to be able to set a different font-size for fullscreen viewing. In the context of a blogpost with a small width, it would allow to not have the terminal cropped with small font when not fullscreen, and a normal font on fullscreen.

**Comment by sickill** [comment]
The above has been released to npmjs.org (currently as 3.0.0-rc.1) and asciinema.org has been updated to use it as well. 

Check out this example recording: https://asciinema.org/a/455413 - resize your browser window, enter/exit fullscreen - it should adjust the terminal and font size in real-time.

**Comment by hybras** [comment]
I've verified that it does. close this?
