### ISSUE TITLE
The scrubbing scrollbar UI hides the bottom line of the terminal -- often the most important line!

### ISSUE THREAD

**Issue by NHDaly** [asciinema/asciinema-player#153]
Most of the typing in any terminal session (once the scrollback has been filled) happens on the very bottom line. But in the Asciinema playback UI (which is otherwise **lovely** 😁❤️), the bottom line is covered whenever you mouse over the video!

This can make it quite difficult to scroll through a video and find the place you were looking for, because you can't see what the user is typing while you're scrolling!

This also makes it extremely difficult to copy/paste from the line that the user is about to enter into the terminal.

(For an example, here is an asciicast i recorded, where a lot of the action is happening on the bottom line, but you can't see it when the scrolling UI is displayed):
<a href="https://asciinema.org/a/DmXipKlztALrzSF0vnrK86Lle"><img alt="ascii screen cast" src="https://asciinema.org/a/DmXipKlztALrzSF0vnrK86Lle.svg" align="center" width="400" ></a>

------------------------

Some ideas/proposals:
- Would it be possible to have the scrollback UI "push up" all the text by one line, so that you can still see the text on the bottom line? Rather than hovering up _over_ the text?
- Or could you just have the scrollback UI be always present? (I'm sure this is less desirable, aesthetically.)
- Or could the scrollback UI be somewhere else besides the bottom? Maybe the top? Or on the side? (The side might be too easily confused with an actual scrollback, which it of course isn't, thanks to things like ncurses.)

**Comment by sickill** [comment]
This has also been discussed in #90.

**Comment by sickill** [comment]
I have potential solution ready in #215. Need to do some cross-browser testing before I merge but it looks promising.

**Comment by sickill** [comment]
#215 has been merged and released in v3.2.0.
