### ISSUE TITLE
24-bit true-color RGB escape codes in iTerm2

### ISSUE THREAD

**Issue by ianthehenry** [asciinema/asciinema-player#154]
For some reason, when using iTerm2 on macOS, RGB escape codes are colon-separated instead of semicolon-separated.

But asciinema-player doesn't know how to parse those, so if you're recording 24-bit color on a mac, you can't play them back with asciinema-player. Here's an example that works great in iTerm2 (and thus local `asciinema play`back), but that does not work with asciinema-player:

https://asciinema.org/a/DXFd3EAnipwXA2MggYkNhX24g

You can workaround this by creating a custom `terminfo` database and forcing it to use semicolons, as demonstrated here:

https://stackoverflow.com/questions/14672875/true-color-24-bit-in-terminal-emacs

iTerm2 will still render and display the semicolon-separated escape codes correctly, so there doesn't seem to be any downside to doing this, but it's unfortunate that asciinema-player doesn't work out of the box for 24-bit color recordings on a mac. (And this problem was... very difficult to diagnose.)

The simple fix would be to support either colon-separated and semicolon-separated escape codes in asciinema-player. But I don't really understand... anything about this. So maybe that's not the right thing to do.

**Comment by sickill** [comment]
This problem seems to be very unusual and likely related to your specific setup.

I'm going to close it, but we can revisit if another poor soul stumbled upon something similar.

**Comment by rockorager** [comment]
I ran across this issue as well. Colon separated is the preferred method by nearly ever terminal I've encountered.

**Comment by sickill** [comment]
Yeah, I take back what I said earlier. We gotta fix it indeed.

**Comment by sickill** [comment]
I need to solve https://github.com/asciinema/avt/issue/9 for this first.

**Comment by sickill** [comment]
Thanks. I'll take a look at their impl.

**Comment by ku1ik** [comment]
I recently created distinct `Params` struct for collecting params (https://github.com/asciinema/avt/blob/28aed2b5a65a4ff07344fd6bc51b8ccb8542389c/src/parser.rs#L33) which should help implementing sub-param handling.

**Comment by ku1ik** [comment]
This has been fixed in 3.8.0 - https://github.com/asciinema/asciinema-player/releases/tag/v3.8.0
