### ISSUE TITLE
AsciinemaPlayer as npm in Next.js

### ISSUE THREAD

**Issue by catalinred** [asciinema/asciinema-player#160]
I have some issues in using AsciinemaPlayer as an npm package to a Next.js app.
This works just fine though when importing the npm package within a basic React app, but not in Next.js.

Whenever I try to
`import * as AsciinemaPlayer from 'asciinema-player';`

I got this response from Next.js
> SyntaxError: Cannot use import statement outside a module.

Can anyone advice here on how to overcome this? Thanks.

**Comment by ethanmick** [comment]
I'm not sure how you fixed it, but I resolved this same issue (Next.js 12.1) this way:

```
useEffect(() => {
  ;(async function () {
    const AsciinemaPlayerLibrary = await import('asciinema-player')
    const currentRef = ref.current
    AsciinemaPlayerLibrary.create(src, currentRef, asciinemaOptions)
  })()
}, [src])
```

Using Next's dynamic import to pull the library in at runtime.

**Comment by catalinred** [comment]
In the end, this is how I did it too.
Thanks for sharing the solution here, this might come in handy for other wandering souls :)
