### ISSUE TITLE
Support cast file fetch with credentials: include

### ISSUE THREAD

**Issue by yarona1993** [asciinema/asciinema-player#161]
Support cast file fetch with credentials: include

file: **src/driver/asciicast.js**
line: 8-28

`function asciicast({ url }, { feed, now, setTimeout, onFinish }, { idleTimeLimit }) {
  let cols;
  let rows;
  let frames;
  let duration;
  let timeoutId;
  let nextFrameIndex = 0;
  let elapsedVirtualTime = 0;
  let startTime;
  let pauseElapsedTime;

  async function load() {
    if (!frames) {
      const res = await fetch(url);
      const asciicast = parseAsciicast(await res.text());
      cols = asciicast.cols;
      rows = asciicast.rows;
      frames = prepareFrames(asciicast.frames, idleTimeLimit ?? asciicast.idleTimeLimit);
      duration = frames[frames.length - 1][0];
    }
  }`

to something like
`
function **asciicast({ url, args = {} }**, { feed, now, setTimeout, onFinish }, { idleTimeLimit }) {
  let cols;
  let rows;
  let frames;
  let duration;
  let timeoutId;
  let nextFrameIndex = 0;
  let elapsedVirtualTime = 0;
  let startTime;
  let pauseElapsedTime;

  async function load() {
    if (!frames) {
      **const res = await fetch(url, args);**
      const asciicast = parseAsciicast(await res.text());
      cols = asciicast.cols;
      rows = asciicast.rows;
      frames = prepareFrames(asciicast.frames, idleTimeLimit ?? asciicast.idleTimeLimit);
      duration = frames[frames.length - 1][0];
    }
  }
`

**Comment by sickill** [comment]
This is great idea, thanks!

**Comment by sickill** [comment]
It's out now.

**Comment by yarona1993** [comment]
thanks!
