### ISSUE TITLE
idleTimeLimit combine with startAt gives false location

### ISSUE THREAD

**Issue by yarona1993** [asciinema/asciinema-player#162]
When limiting the idle time with "idleTimeLimit" - the total cast time gets shorten
So when combine with startAt option - you gets false location

**Comment by sickill** [comment]
Good catch! This should be pretty easy to fix.

**Comment by cmprmsd** [comment]
Was about to open the exact same issue! :D 
Good I had a look at the open issues first :) 

Subscribed. :+1:

**Comment by sickill** [comment]
Btw, this hasn't been document (which I fixed now in 27d9681e76a4be59606b139374e4c06cbe9ac6e7), but you can specify `startAt: '50%'` and it will start at a given percentage of total recording duration. This variant works well with `idleTimeLimit` already.

**Comment by cmprmsd** [comment]
Thanks for working on this 😁 
Giving seconds will not work yet but is planned right?

**Comment by sickill** [comment]
Yes, I agree with you on the expected behavior here, this makes sense.

**Comment by mathieu-aubin** [comment]
great catch! well done on taking the time to notify the project!

**Comment by sickill** [comment]
The fix is going to be released shortly in 3.0.0-rc.2.

**Comment by cmprmsd** [comment]
This one does also work now. Cool stuff!

**Comment by yarona1993** [comment]
thanks!

**Comment by rgwood-dd** [comment]
@ku1ik I think there are still issues in this area; maybe a regression occurred? Details below but just let me know if I should create a new issue.

**Steps to Reproduce**

1. Put the following cast file and html file in a directory: [asciinema-repro.zip](https://github.com/user-attachments/files/16181495/asciinema-repro.zip)
    1. The cast file is a recording of me running `ls` twice, once at ~3s and once at ~54s
    2. The html file uses Asciinema Player v3.8.0 and hardcodes `startAt: 10, idleTimeLimit: 2`
2. Use something like [`http-server`](https://www.npmjs.com/package/http-server) to serve them up
3. Open `player.html` in a browser, observe that the playback starts at the end of the recording and is stuck in "playing" mode forever

<img width="1192" alt="Screenshot 2024-07-11 at 10 45 25" src="https://github.com/asciinema/asciinema-player/assets/163153147/f3d6f579-47e2-44d7-a870-81c882678466">
