### ISSUE TITLE
Keyboard fast-forward and rewind not working as intended

### ISSUE THREAD

**Issue by cmprmsd** [asciinema/asciinema-player#164]
When I seek forward or backward according to the documentation it should skip 5 seconds.

`← / → - rewind 5 seconds / fast-forward 5 seconds`

However, the browser skips 10% foward and backword. 
This is an issue when I search in longer terminal recordings. As it skips e.g. 11minutes per keyboard press which is far too much.

Skipping 5 seconds is fine. How can I re-enable this behaviour?

Also I noticed that the control-hud disappears if the player is in fullscreen and the terminal does not stretch to the bottom of the screen.

When the mouse moves from the terminal area to the black area the menu bar disappears:
![image](https://user-images.githubusercontent.com/73472903/149796938-774e3ec1-1043-426a-8ed2-51444e206454.png)

**Comment by sickill** [comment]
Good catch. I believe I thought fast-forward by 10% makes more sense than by fixed number of seconds, and after implementing it this way I forgot to update docs. I see your point though, for longer recordings this may be inconvenient indeed. Maybe we do 5s jumps for left/right arrows and 10% jumps when shift key is pressed additionally? 🤔 

That problem with scrollbar being stubborn in fullscreen is know to me, yeah. I thought it was only me feeling this pain though :) I'll see what can be done about it.

**Comment by cmprmsd** [comment]
That's a good idea 👍 
You could also think about velocity e.g. pressing right once equals 5 seconds. After pressing it three times or so it should skip 10s then 20s, 30s and so on. I think I saw this implementation somewhere. Going in the other direction or pause/play would of course reset the velocity in order to do the fine grained search again. 

But the two options with and without shift would already improve it a lot. 😇

**Comment by sickill** [comment]
The fix will be released soon in v3.0.0-rc.2. I'll handle the control HUD issue separately.

**Comment by sickill** [comment]
#171

**Comment by cmprmsd** [comment]
Whoop whoop! Thank you! I'll try it asap :)

**Comment by sickill** [comment]
It's out :)

**Comment by cmprmsd** [comment]
Very nice. I can confirm the fix :+1:
