### ISSUE TITLE
v3 is missing external play/pause/etc control methods

### ISSUE THREAD

**Issue by angelsl** [asciinema/asciinema-player#165]
v3 is missing the programmatic control methods that were present in v2.

I use Asciinema in presentations, and those methods were useful for me. In Reveal.js, I have Asciinema as a fragment, and activating the fragment starts the player, while deactivating the fragment (going to the previous fragment) stops the player. That lets me control the player even using a simple remote presenter that has only next/back buttons.

I will probably add them myself and raise a PR when I have time if someone else doesn't get to it.

**Comment by lhr0909** [comment]
Came across the same issue. I am trying to render the player in Remotion for rendering videos, and would like to synchronize the video playback with the asciinema player. So being able to get the total time for the cast from the outside will be ideal.

**Comment by sickill** [comment]
Check out #173 , it brings back API for programmatic control. If it looks good enough then I'll release it shortly as new RC version.

**Comment by sickill** [comment]
Merged and released #173 as 3.0.0-rc.3 :rocket:
