### ISSUE TITLE
Strange sliding effect (misrendering)

### ISSUE THREAD

**Issue by mikehearn** [asciinema/asciinema-player#169]
https://asciinema.org/a/1GiQf02fDHGOShnBBmQC4LMJi

The above cast plays fine locally with `asciinema play`, and the app works great in iTerm2. But during playback you can see the right hand side of the unicode progress bars "slide" to the left, even though in the real terminal they were pinned to the right hand side.

My guess is that the unicode bar symbol is causing some sort of mis-measurement?

**Comment by sickill** [comment]
Yeah, this is likely related to the lack of support for wide characters (wcwidth).

**Comment by sickill** [comment]
#185

**Comment by mikehearn** [comment]
Yep, thanks! :)
