### ISSUE TITLE
Which line the corrupted cast file is from?

### ISSUE THREAD

**Issue by bugrabilmez** [asciinema/asciinema-player#170]
Hello,

We are creating automatically the cast file. Sometimes special characters can cause problems to us. This problem arises with the json.parse function, but I am modifying the source code to find which line it is. It will be more understandable to write the json.parse error with the line. You can improve the code in asciicast.js as follows:

```
function parseCastLine(string) {
  try {
    return JSON.parse(string);
  } catch(err) {
    console.error(`Cast Line Parsing Error, line: ${string}, this line can not be parsed.`);
    throw new Error(err);
  }
}

function parseAsciicastV2(jsonl) {
  const lines = jsonl.split('\n');
  const header = JSON.parse(lines[0]);

  if (header.version !== 2) {
    throw 'not asciicast v2 format';
  }

  const frames = new Stream(lines)
    .drop(1)
    .filter(l => l[0] === '[')
    .map(l => parseCastLine(l))
    .filter(e => e[1] === 'o')
    .map(e => [e[0], e[2]]);

  return {
    cols: header.width,
    rows: header.height,
    idleTimeLimit: header.idle_time_limit,
    frames: frames
  }
}
```

Sample Cast Line:
[1.32,"o","""]

Sample Error:
Unhandled Promise rejection: Cannot read properties of undefined (reading '1') ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read properties of undefined (reading '1')
    at index.js:3798:13
    at index.js:3442:11

**Comment by sickill** [comment]
Thanks, but I believe that complicating the code to produce slightly better error when a tool creates invalid recording file is not worth it.
