### ISSUE TITLE
Unexpected control behavior on vertically-oriented video in fullscreen mode

### ISSUE THREAD

**Issue by inflatador** [asciinema/asciinema-player#171]
Hello Asciinema,

When viewing vertically-oriented video such as [this](https://asciinema.org/a/WqirmPmHSlHa0LzN5dZLxgCAR) in fullscreen mode, the controls (as in pause/play/timeline) stretch out across the entire horizontal space of the window. 

However, the controls don't respond unless you move your cursor directly over the video (NOT within the black bars on the side, even though the controls are stretched out that far) . This leads to a frustrating game of hide-and-seek when you're trying to use the controls.

Requesting to either change the controls so they fit the video exactly, or allow interaction with the controls within the black bars on the sides of the video.

Tested on Mac OS with Firefox.  

Thanks for your time! Please let me know if you need more information.

**Comment by sickill** [comment]
I agree, this behaviour can be frustrating. I hope to improve this before releasing the final 3.0 version.

**Comment by sickill** [comment]
I'll release this fix soon in v3.0.0-rc.2.

**Comment by sickill** [comment]
It's out now.
