### ISSUE TITLE
Asciinema Player Tag support

### ISSUE THREAD

**Issue by hybras** [asciinema/asciinema-player#172]
Was support for the tag removed in v3? Tried upgrading and my pre existing pages stopped working.

**Comment by sickill** [comment]
Yeah, the old implementation was based on the deprecated [document.registerElement](https://developer.mozilla.org/en-US/docs/Web/API/Document/registerElement) API so I removed it in the 3.0 rewrite.

It seems new [customElements.define](https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/define) API has stabilized, so we could add the tag support back.

**Comment by hybras** [comment]
The js api maps nearly 1 to 1 to the tag. I'm using a template engine, which makes it easy to rewrite my site to use that instead.
