### ISSUE TITLE
AsciinemaPlayer is not defined

### ISSUE THREAD

**Issue by themikeambrose** [asciinema/asciinema-player#177]
I'm trying to use the latest 2.6.1 player to be able to run it locally on my website. I am using the generic example from the readme and am unable to get it to work as it returns the following error in dev console.

`Uncaught ReferenceError: AsciinemaPlayer is not defined at test.html:13:5`

I have the following in test.html:

```
<html>
<head>
  ...
  <link rel="stylesheet" type="text/css" href="https://REDACTED.com/billing/asciinema/asciinema-player.css" />
  ...
</head>
<body>
  ...
  <div id="demo"></div>
  ...
  <script src="https://REDACTED.com/billing/asciinema/asciinema-player.min.js"></script>
  <script>
    AsciinemaPlayer.create('https://REDACTED.com/billing/asciinema/casts/123.cast', document.getElementById('demo'));
  </script>
</body>
</html>
```

 The asciinema-player.css, asciinema-player.min.js files are accessible and in the right place. The 123.cast file is accessible as well.
 I replaced my domain with REDACTED and replaced the original cast ID number in the file with 123.

**Comment by themikeambrose** [comment]
I build from the latest rc and it works fine, so this is just an issue with the 2.6.1 pre-built files.

**Comment by sickill** [comment]
That's correct. README on develop branch applies to latest version. README on master applies to 2.6. I'll release 3.0 soon, addressing a few final things.
