### ISSUE TITLE
Scroll options for horizontal and vertical

### ISSUE THREAD

**Issue by kapilggg10** [asciinema/asciinema-player#178]
It will be great if we provide scroll options in horizontal and vertical direction for these reasons:
1. Avoid resizing of font in case of window resizing.
2. Avoid cutting text on right side of the player and bottom of the player due to resize in window.

**Comment by sickill** [comment]
Automatic scaling of the font is a feature and desired behavior. Also in player v3.0 the text on the right/bottom side of the terminal is no longer cut off during browser window resizing thanks to the mentioned font scaling.
