### ISSUE TITLE
Play Icon in centre sticks there, if we slides the slider before clicking on the play Icon.

### ISSUE THREAD

**Issue by kapilggg10** [asciinema/asciinema-player#189]
Initially Play Icon is there in the centre, It will go away if you play the video from play icon.
But It is stuck if you slide time from slider and then play video using play icon.

Steps:
1. Load Asciinema-player.
2. Click on slider and slide video to some new time (ex: 00:37).
3. Click on Play Icon in control-bar.

We can see that a Play Icon is stuck in the centre in this case.

**Comment by sickill** [comment]
I believe I already fixed that in master but not released yet. If so I'll cut a new patch release shortly.

**Comment by kapilggg10** [comment]
@sickill If this issue is fixed, please attach the release version of the patch once released. otherwise I can pick this issue and can create a PR with a fix for this.

**Comment by sickill** [comment]
It's been fixed in https://github.com/asciinema/asciinema-player/commit/998447fa2828a60c0e6e6da131729c6b4e724677 and part of 3.0.0 release.
