### ISSUE TITLE
missing dist files in 3.0.1 release

### ISSUE THREAD

**Issue by daniel-baumann** [asciinema/asciinema-player#190]
Hi,

it would be nice if you could add asciinema-player.css and asciinema-player.min.js in
  https://github.com/asciinema/asciinema-player/releases/tag/v3.0.1
as assets like for the previous releases.

Regards,
Daniel

**Comment by sickill** [comment]
Ah, good catch, thanks.

**Comment by sickill** [comment]
Just fixed it.
