### ISSUE TITLE
CJS / ES Module when using library with Vite Dev / Rollup

### ISSUE THREAD

**Issue by JulianCataldo** [asciinema/asciinema-player#196]
Hello there!
First of all, thank you for this awesome package 👍🏻 
That's why I'd like to report this minor issue, because I guess some other people have encountered it:

```
asciinema-player doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module
(i.e. it doesn't have "type": "module" or an .mjs extension for the entry point).
Please contact the package author to fix.
```

It appears on a vanilla Astro JS installation, which is using Vite Dev Server + Rollup under the Hood.

Cheers

**Comment by sickill** [comment]
I'm not sure why this happens. We use Rollup to produce ES module, see here https://github.com/asciinema/asciinema-player/blob/77a92b3e53ed2799604849105a1c0d78f6c3b57f/rollup.config.js#L37

**Comment by JulianCataldo** [comment]
Mhhh, I see.
I will keep an eye on this during my developments, and keep you in touch here, if it's an environment specific issue, or some kind of mismatch from I don't know where 😅
If needed, I'll make a minimal repro. repo.

👋
