### ISSUE TITLE
ResizeObserver loop limit exceeded Error thrown when window resizes

### ISSUE THREAD

**Issue by Georgegriff** [asciinema/asciinema-player#198]
I've been noticing this error in our sentry i've reproduced it on the ascii cinema website

### Reproduction steps:
0. Go to https://asciinema.org/ (or any page which includes the player)
1. Add in this global error console logger in browser (chrome) dev tools: 
```js
window.addEventListener('error', function(e) { console.log('Error', e); });

```
2. Resize the browser a few times you should see the error logged

I'm not sure if this actually caused problems or is just noise, but I thought it was worth raising

![image](https://user-images.githubusercontent.com/9056958/196398526-e3e4c300-4e65-49ac-b0e9-0c9385fe5112.png)

**Comment by wolfogre** [comment]
The same problem. I added an asciinema player to my web site with a front end framework which would listen error event, and it keeps reporting this error when I'm resizing the browser.

**Comment by sickill** [comment]
On what browsers do you see that error?

**Comment by wolfogre** [comment]
> On what browsers do you see that error?

Chrome.

**Comment by sickill** [comment]
I've tried to reproduce it on Chromium 110.0.5481.177 and Firefox 110, both on Arch Linux, as well as on latest versions of Safari, Chromium and Firefox on macOS. Unfortunately I'm not able to trigger the error.

Any hints on how to reproduce? Any particular way I should resize, or a specific recording on asciinema.org where it occurs more often?

**Comment by wolfogre** [comment]
https://user-images.githubusercontent.com/9418365/222039017-c8f976a9-1aa2-40db-82eb-27f3a9076f7b.mov

**Comment by sickill** [comment]
Awesome, thanks! I tried on several recordings but haven't tried on the front page of the site, where indeed I can reproduce easily. Now let's see what's going on.

**Comment by sickill** [comment]
Found it and fixed it. I'll try to release it as 3.1.2 ~tomorrow.

**Comment by sickill** [comment]
3.1.2 is now released with the fix.
