### ISSUE TITLE
Unicode monospace width issues for '⬤'

### ISSUE THREAD

**Issue by Mononofu** [asciinema/asciinema-player#209]
The '⬤' unicode character (U+2B24 - Black Large Circle) does not seem to be displayed correctly in my recording, it takes up more width than it should: [screenshot](https://www.dropbox.com/s/2rw5frybj4aj1em/2021-12-20_21%3A20.39.png), [recording](https://asciinema.org/a/457334)

I tried both using Chrome on Ubuntu 20.04 and Chrome on Android 12.

Interestingly, when I use the image preview embedding from asciinema, the width is correct but instead the colors are not shown correctly:

[![asciicast](https://asciinema.org/a/457334.svg)](https://asciinema.org/a/457334)

The color issue may be due to the fact that I'm using 24-bit colors?

**Comment by ku1ik** [comment]
The recently release 3.7.1 version of the player got several improvements around rendering accuracy, mostly fixing positioning and alignment of various character groups (ascii drawing, block elements, Powerline symbols, CJK, emoji). It should look much better than before now. 

Those fixes were also applied to the SVG previews in asciinema server, they should look consistent in most cases.

The first recording you linked still doesn't look as it's supposed to, but the 2nd one seems to be ok. This is how it looks for me now:

![image](https://github.com/asciinema/asciinema-player/assets/17589/89c9fab7-dc04-4187-b5e4-d9b8e557ce64)
