### ISSUE TITLE
Add ARIA roles, labels, and tabindex values to controls for accessibility.

### ISSUE THREAD

**Issue by bmmcginty** [asciinema/asciinema-player#211]
I just submitted a PR (#210) to add some basic screen reader support to asciinema-player.
Screen readers turn visual text into spoken text, and sometimes braille, for use by blind computer users.
Asciinema-player can be controlled via keyboard, but this control doesn't affect the way screen readers display the console output that gets displayed by the player.
 
I don't want to add pages of background, but I'll be glad to expand below as requested by developers or contributors.
 
A note. I realize this work is somewhat haphazard.
These are the minimal viable changes to make asciinema-player usable to myself as a screen reader user.
I don't have a perfect knowledge of all the web accessibility APIs, roles, etc.
Nor do I want to try making sweeping changes to the player.
 
Fixes:
1. Each new line of terminal output must either be changed not to use span elements, or to use an ARIA role that lets the screen reader know that it's looking at a new line of output. (Span elements, to screen readers, make the text look like one never-ending line.)
I have added a role of "paragraph" to each span with a line class, to split the output into multiple lines.

2. Icons without labels and appropriate roles don't show up to screen readers, or if they do, they don't show up as clickable controls.
I have added role="button" to SVGs and span elements that appear as controls to typical users.

3. Without tabindex attributes, non form-input controls aren't focusable by the keyboard, which is needed for screen readers to interact with them.
I have added tabindex attributes to the output <pre> element, as well as the interactive controls.
This change is the only one that should affect non-screen reader users.
If a user uses the tab and shift+tab keys to move around a webpage, their focus will move across these controls, where it previously would not have.

**Comment by joachimesque** [comment]
I second the need for better accessibility in the player. Interactive elements should use the right HTML elements (`button` for example, instead of just being a clickable `span`) or have the right attributes and interaction.

**Comment by sickill** [comment]
Merged #210 now so will close this issue. We can look at making buttons real `<button>` elements :+1: separately.

**Comment by joachimesque** [comment]
Thank you!
