### ISSUE TITLE
Missing dist files in 3.1.1 release

### ISSUE THREAD

**Issue by nyg** [asciinema/asciinema-player#213]
Hello,

I can't find the following files in the latest release: `asciinema-player.css` and `asciinema-player.min.js`. Could you please add them?

Thanks a lot,
nyg

**Comment by sickill** [comment]
Right, forgot about that. Just added the files to 3.1.1 release.

Would be nice actually to figure out how to automatically upload the assets in this release action: https://github.com/asciinema/asciinema-player/blob/develop/.github/workflows/release.yml
