### ISSUE TITLE
Console debug statements may be unnecessary

### ISSUE THREAD

**Issue by beornf** [asciinema/asciinema-player#214]
Really a minor thing and already filtering them out in Chrome debugging tools.

Seeing a few statements like these after the v3 release:
https://github.com/asciinema/asciinema-player/blob/52cfc6adbf96f8512109c89c1f2aeab35b2f3b96/src/components/Player.js#L113
https://github.com/asciinema/asciinema-player/blob/52cfc6adbf96f8512109c89c1f2aeab35b2f3b96/src/components/Player.js#L174

**Comment by sickill** [comment]
They're helpful though. What's wrong with this?

**Comment by sickill** [comment]
I guess you, as a library consumer don't care about those and would rather avoid this noise, and me as a developer of it appreciates this extra info.  Maybe an explicit option to opt-in for this logging would solve it nicely.

**Comment by beornf** [comment]
Or do you think I should strip out console statements with webpack in production.

**Comment by sickill** [comment]
I have a patch which addresses this, I'll wrap it up shortly. Thanks.
