### ISSUE TITLE
Best practices to create the asciinema player with Reveal.js?

### ISSUE THREAD

**Issue by mickaelbaron** [asciinema/asciinema-player#216]
Hi,

I'm using both Asciinema-Player and Reveal.js and I encounter problems for displaying several asciinema sessions.

This problem is described as follows. Sometimes we can have three asciinema sessions which displayed, sometimes four, sometimes one. To solve the problem, we need to refresh the web browser on the current Reveal.js slide where the asciinema session is hidden. Hidden asciinema players are created, but the size is null.

I created a Github repository to reproduce the problem => https://github.com/mickaelbaron/revealasciinema. We create the asciinema player only when the slide (which must contain the asciinema player) is displayed (thanks to the Reveal.js' events).

In this Git repository (https://github.com/mickaelbaron/revealasciinema), I propose a workaround or a best practice to create the asciinema player. I do not think is an issue related to Asciinema Player, it should be seen more as a requirement from Reveal.js.

I hope this will help you if one day you have this issue.

Best

PS: one year ago, I posted a message to the Asciinema forum => https://discourse.asciinema.org/t/asciinema-reveal-js-display-issue/618.

**Comment by sickill** [comment]
Have you tried `{ fit: "both" }` option? It's meant to fit the player to the available space in container, taking both width and height into account. I see in your workaround html you used `{ fit: "none" }`, which could help in some scenarios but in general is not recommended.

I think the problem with Reveal + asciinema-player could be as follows: asciinema-player needs a container element that has non-zero width/height when it initializes. It has auto-resize support, which triggers when the container element gets resized, but maybe Reveal is doing something which prevents this, or even breaks the initial size measurements in the first place.

**Comment by sickill** [comment]
I've made some improvements related to player initialization, specifically how it gets font metrics, here https://github.com/asciinema/asciinema-player/commit/92333590eece6a63d79ae399e5970b267bf45219

I tested this with your revealasciinema example and it seems to work fine.

**Comment by mickaelbaron** [comment]
Dear @sickill,

It is a great news. I will test this new fix and let you know if it works.

Best

**Comment by sickill** [comment]
I've released v3.3.0 with the above fix.

**Comment by mickaelbaron** [comment]
Dear @sickill,

It's working, so cool. My workaround is no longer useful.

Thank you a lot

Mickael

**Comment by sickill** [comment]
Glad to hear!
