### ISSUE TITLE
Player does not show in dropdown in Firefox

### ISSUE THREAD

**Issue by fzs** [asciinema/asciinema-player#229]
When placing the asciinema player in an initially hidden dropdown, for example a HTML `details` element, then the player will not display in Firefox when the dropdown is opened. This works in Chrome.

I tested this on Windows 10 with Chrome 106.0.5249.62 and Firefox 105.4.

The `div` with class `asciinema-player` that is created is stuck at `height: 0px`. When removing the attribute, it is recreated when the mouse moves over the player, making the player disappear again.

Example page which reproduces the issue:
[asciinema_v3_dropdown_bug_229.zip](https://github.com/asciinema/asciinema-player/files/11301098/asciinema_v3_dropdown_bug_229.zip)

**Comment by sickill** [comment]
What version of the player do you use? Latest (3.3.0) had improvements around initialization/height.

**Comment by fzs** [comment]
I am using the latest release, 3.3.0.

Trying this with a CSS-only dropdown, i.e. an `input` and a hidden `div` it neither works in Chrome nor Firefox. With a `details` tag it at least works in Chrome.

**Comment by sickill** [comment]
Before you switch back to 2.6, you can try using `fit: false` option with the latest one. Like this:

```javascript
AsciinemaPlayer.create('/demo.cast', document.getElementById('demo'), { fit: false });
```

This switches the player to use sizing behaviour from 2.x. Not 100% sure it will fix it in this particular case but it's worth a try.

**Comment by fzs** [comment]
No, that doesn't help, I had already tried that. I had also experimented with other settings but to no avail.
I would look into it closer, as I think this would be useful behaviour if it worked, but I am afraid I don't know enough about JS development.

**Comment by sickill** [comment]
I'm not sure if there's anything actionable here anymore (instantiating player in hidden elements is not supported/recommended), so I'll close this. I hope you got it working one way or another :crossed_fingers:
