### ISSUE TITLE
How to unload or reload existing player? Deleting from DOM and re-adding causes playback errors.

### ISSUE THREAD

**Issue by devvyn** [asciinema/asciinema-player#23]
I can't find any official way to change the file name after the player is initialized by JavaScript. How should I un/re-load the player in the browser?

**Use case**: I'm making a projector page that lists the available asciicast files on the server and tries to re-initialize the player when the user clicks one of the file names. I'm using jQuery to create the player with a default recording when the page loads. I'm also using jQuery to bind click events to the files in the list, which removes the existing player from the DOM and calls the CreatePlayer function with the new file name.

**The problem**: only the first recording plays. Any players subsequently created always fail during playback—even if it's the only player on the page.

**Work around**: reload the whole page every time the file name property needs to be altered programmatically.

I assume some variables or properties are left in the window scope when the player node is removed from the DOM, but I don't know how to work around the issue other than to force a full page reload every time. Any advice would be appreciated.

**Comment by sickill** [comment]
What does "fail during playback" mean?
Can you create a simple HTML page reproducing this problem?

**Comment by SpEcHiDe** [comment]
I think @devvyn meant a page like this: [Dummy Page](https://shrimadhavuk.me/MyAsciiNemas/index.html)
A new player is created when I click on the links for the first time!
But, subsequent clicks results in errors!!

**Comment by sickill** [comment]
You can try the latest version of the player (v2.4.0), it should solve the problems with deleting from DOM and re-adding.

**Comment by SpEcHiDe** [comment]
@sickill  It works! At the time of posting the above comment v2.4.0 was not released! :p
