### ISSUE TITLE
Write to GIF?

### ISSUE THREAD

**Issue by dannguyen** [asciinema/asciinema-player#24]
The standard functionality works beautifully for me...but once in awhile (such as embedding into Github-formatted pages), having a GIF version of the output would be really nice. How feasible would it be as a feature, given the innards of how the player currently works?

**Comment by techtonik** [comment]
https://github.com/tav/asciinema2gif/

**Comment by sickill** [comment]
I think the best way to implement this would be to use player's VT (https://github.com/asciinema/asciinema-player/blob/master/src/asciinema/player/vt.cljc) and its view (https://github.com/asciinema/asciinema-player/blob/master/src/asciinema/player/view.cljs), and the PhantomJS script that is currently used for generating .png screenshot (https://github.com/asciinema/asciinema.org/blob/master/bin/rasterize).

This would give the best quality (the same as we have for .png on asciinema.org now), and would produce .gif with variable frame times (constant frame rate is unnecessary in our case and would produce bigger files - this is what https://github.com/tav/asciinema2gif does right now).

/cc https://github.com/asciinema/asciinema.org/issues/187
/cc https://github.com/asciinema/asciinema-player/issues/26
/cc https://github.com/tav/asciinema2gif/issues/24

**Comment by sickill** [comment]
Please try out https://github.com/asciinema/a2gif (I implemented the idea from https://github.com/asciinema/asciinema-player/issues/24#issuecomment-217708694).

**Comment by sickill** [comment]
If you append `.gif` to your recording URL now you get instructions on how to generate gif animation for it. Example: https://asciinema.org/a/113463.gif

**Comment by techtonik** [comment]
I can't test this ability right now, but I will certainly do when I find the time. Thanks!

**Comment by oconnor663** [comment]
I'm seeing a failure from the docker instructions provided by that `.gif` link:

```
docker run --rm -v $PWD:/data asciinema/asciicast2gif https://asciinema.org/a/tw4lOrVzXMcxdBeOnHBIOvvL8.cast demo.gif
```

```
==> Combining 105 screenshots into GIF file...
Killed
gifsicle:<stdin>: empty file
/app/main.js:697
```

**Comment by rosscdh** [comment]
This issue still seems relevant?
