### ISSUE TITLE
UI will not show up when pressing hotkeys

### ISSUE THREAD

**Issue by cmprmsd** [asciinema/asciinema-player#242]
**Describe the bug**
Since some ui changes the progress bar is now below the last line, which is awesome!
However, the bar always disappears during playback. It does not show up again when I e.g. move through the file with left and right hotkeys. When searching I'd expect the UI to be visible again.

**To Reproduce**
1. play a video
2. skip forward and backward. 
3. The ui still disappears

**Expected behavior**
The UI should appear again when a hotkey is pressed.

**Versions:**
 - OS: Linux
 - Browser: Firefox latest
 - asciinema player: 3.5.0

**Comment by sickill** [comment]
I wouldn't say it's a _bug_, it's just one way of handling it. What you expect makes sense as well though.

Btw, see https://github.com/asciinema/asciinema-player#controls - you can make it always visible.

**Comment by cmprmsd** [comment]
I agree. Only an unexpected behavior when I compare it to other platforms e.g. YouTube. :) 

Oh! How could I miss this! :disappointed: 
Thanks for pointing this out :heart:

**Comment by sickill** [comment]
I'm glad you like the new option.

I think I'll keep this issue open for now, we can revisit the behavior at some point.
