### ISSUE TITLE
why does it not render sixel?

### ISSUE THREAD

**Issue by aicynide** [asciinema/asciinema-player#245]
To make life of the project maintainers easier please submit bug reports only.

This is bug tracker for asciinema web player. If your issue seems to be with another component (cli recorder, server) then open an issue in related repository.

Ideas, feature requests, help requests, questions and general discussions should be discussed in project's Discussions instead: https://github.com/orgs/asciinema/discussions

If you think you've found a bug or regression, go ahead and delete this message and fill in the details below.

-----

**Describe the bug**

Its not rendering sixel

**To Reproduce**
1. Record sixel session
2. Upload
3. Play in asciinema.org

**Expected behavior**

Render sixel

**Screenshots**

**Versions:**
 - OS: arch linux
 - Browser Librewolf 121
 - asciinema player: 3.3.3

**Additional context**

**Comment by ku1ik** [comment]
Sixel support is not planned at the moment, sorry.
