### ISSUE TITLE
UI width not correctly computed

### ISSUE THREAD

**Issue by momiji** [asciinema/asciinema-player#247]
Hi, I had an issue on the width inside a mkdocs display, and finally find the width was calculated in another place than the one the player will show up.

I haven't been able to identify the reason, but in firefox (this is the latest version as of today), I have strange results for maybe the 2 last columns not always showing correctly.

This is easy to test: just open https://asciinema.org/a/448073 and slowl decrease the width of the browser.
You'll see the last columns can be hidden (overflow) at some size.

On my side, an 120ch width is not displayed correctly even in full screen (2560+), but only in 100%. In 110%, it displays correctly, but I don't know why.

My impression is the "scale" factor is not computed correctly, but I was not able to figure why. Th font-size is around 160% instead of 155% to have chars displayed.

Any idea?

**Comment by momiji** [comment]
This is very strange, this issue does not shw in chromium (so I guess not on Chrome/Edge also), but only in firefox.

**Comment by ku1ik** [comment]
Can't reproduce with https://asciinema.org/a/448073. It looks fine in FF for me. Maybe you have some FF extensions enabled which affect the page?

**Comment by ku1ik** [comment]
Do you still experience this problem?
