### ISSUE TITLE
Artifacting on asciinema.org - looks good in CLI player

### ISSUE THREAD

**Issue by weitzman** [asciinema/asciinema-player#253]
**Describe the bug**
Hi all. I'm seeing some odd artifacting when my file is played on [asciinema.org](http://asciinema.org/). 

Start at the 30 second mark at https://asciinema.org/a/je9ZXdryLGlRxrizTnX574tcZ?t=30. I edit the line with ‘field_number_of_servings’ but the line above starts to obscure it - field_media_image. This artifacting does not happen when I play in my CLI so I think the source file is OK, and its a web player bug?

**Versions:**
 - OS: Recorded on Linux
 - Browser Firefox 119
 - asciinema player: whatever is on asciicinema.org

**Comment by ku1ik** [comment]
Looks like you've overriden the number of terminal rows from recorded 40 to 30 in recording settings. This is too little to fit all nano's output, which needs at least 34 rows in case of this recording. Overriding terminal size for recordings with full screen programs like nano/vim/top is usually going to break the rendering. I think those settings need a warning text about it.

I've updated the number of rows on your recording to 34 and now, I believe, it looks correct.

**Comment by weitzman** [comment]
Thank you!
