### ISSUE TITLE
FYI, hit unreachable!() in webassembly player

### ISSUE THREAD

**Issue by tmpfs** [asciinema/asciinema-player#257]
Not a major issue but I think this could be handled more gracefully.

If the first meta data line of a `.cast` file has `width` and `height` as zero the webassembly in the player hits an `unreachable!()` block.

I noticed this because somehow recording a in a pty (without passing `--rows` and `--cols`) ended up with zero for width and height - i guess something about the pty affects how the terminal size is reported.

I fixed it with explicit `--rows` and `--cols` so it's not a problem, maybe just choose default width and height (80x24)?

**Comment by ku1ik** [comment]
Ah, I suppose you record with `anticipate` :)
