### ISSUE TITLE
Convert recording to gif

### ISSUE THREAD

**Issue by techtonik** [asciinema/asciinema-player#26]
https://github.com/tav/asciinema2gif/ contains code that uses rendered web page from asciinema website to convert video. One of the popular requests is to convert local recorded session - https://github.com/tav/asciinema2gif/issues/24 How hard it is to achieve that?

**Comment by sickill** [comment]
Closing as this is duplicate of #24.

**Comment by sickill** [comment]
Please try out https://github.com/asciinema/a2gif (I implemented the idea from https://github.com/asciinema/asciinema-player/issues/24#issuecomment-217708694).

**Comment by techtonik** [comment]
That's cool. I will definitely try this the next time I need to record something as a tutorial.
