### ISSUE TITLE
No colors in web player for a recording made from foot

### ISSUE THREAD

**Issue by GoldsteinE** [asciinema/asciinema-player#268]
**Describe the bug**
Terminal recording made on foot terminal (`TERM=foot`) plays with no colors in Neovim on `asciinema.org`, but shows correct colors with `asciinema play`.

**To Reproduce**
1. Start the foot terminal, start recording
2. Open Neovim with truecolor colorscheme
3. Upload recording to `asciinema.org`
4. Play it and see there’re no colors.

**Expected behavior**
Colors are preserved.

**Screenshots**
Example of a broken recording: https://asciinema.org/a/yjpYgMrn2lzC5cyGYoO1MAOg4

**Versions:**
 - OS: NixOS 24.11 (Vicuna)
 - Browser: Firefox 130.0
 - asciinema player: not sure, whatever the version is on `asciinema.org` on 2024-10-04.
 - asciinema CLI: 2.4.0
 - foot terminal: 1.18.1 +pgo +ime +graphemes -assertions

**Additional context**
Colors work with `asciinema play` even when recording is played on a different terminal, so I think the problem is with the Web player.

**Comment by GoldsteinE** [comment]
GIF generated by agg is also broken, so it’s probably an issue with avt? Should I re-file it there?

**Comment by GoldsteinE** [comment]
Yes, I think it boils down to avt not supporting the form of truecolor foot uses. In particular, this sequence:
```
\u001b[38:2::141:160:214m foo
```
shows `foo` in purplish color in foot, but is not recognized by avt.

**Comment by ku1ik** [comment]
Interesting. So there was a fix for this type of sequence in avt [here](https://github.com/asciinema/avt/pull/17), and 3.8 release of asciinema player includes the fix. asciinema.org uses 3.8 already (https://github.com/asciinema/asciinema-server/blob/a5ab9d14212a38ee5eeca774a72e8da870e5139f/assets/package.json#L15).

**Comment by ku1ik** [comment]
Now I see there's a double `:` in that sequence right after `38:2`, which may be the culprit 🤔

**Comment by GoldsteinE** [comment]
I filed a PR fixing this and explaining the double colon: https://github.com/asciinema/avt/pull/18

**Comment by ku1ik** [comment]
Thanks!

**Comment by ku1ik** [comment]
Just deployed the fix to asciinema.org. Your recording seems to look fine to me now.

**Comment by GoldsteinE** [comment]
Thanks!

**Comment by GoldsteinE** [comment]
There’s another problem visible on this recording: when the window is narrow, the word `master` in prompt is truncated. I’ll investigate this later.

**Comment by ku1ik** [comment]
Ok. Not sure where/when this happens (looks fine for me), so feel free to open a dedicated issue when you investigate.
