### ISSUE TITLE
Incorrect terminal width on Firefox

### ISSUE THREAD

**Issue by robmv** [asciinema/asciinema-player#28]
On Firefox (46 Linux) a recording of 80 columns does not display as 80 columns but smaller. The CSS is assigned something like style="width:80ch;...." but only when that "width" value is removed the terminal show the correct size.

Testing with Chrome do not expose the same problem.

**Comment by sickill** [comment]
What Linux distro?

**Comment by sickill** [comment]
What happens when you change `80ch` to `40ch` in Firefox's inspector? Does it resize?
Is it happening directly on asciinema.org, in embedded player, or self-hosted player?

**Comment by robmv** [comment]
Distro is Fedora 23 x86_64. It happen on asciinema.org. When I change the size to 40ch it resize to half the previous size, but it still is smaller that 40ch on Chrome

See (top is Firefox, bottom is Chrome)

![ff_vs_chrome_40ch](https://cloud.githubusercontent.com/assets/1652983/15358672/4b3a7ba8-1ccf-11e6-9fb9-5840d3152cf2.png)

**Comment by robmv** [comment]
Note: tested on Firefox profile with no extensions and Firefox developer edition too, same wrong width

**Comment by sickill** [comment]
Thanks, will investigate.

**Comment by sickill** [comment]
Do you have Bitstream `Vera Sans Mono` font installed? What's the font to which `monospace` points to in FF and/or Fedora?

**Comment by robmv** [comment]
monospace points to DejaVuSansMono.ttf: "DejaVu Sans Mono" "Book"

    # fc-match monospace
    DejaVuSansMono.ttf: "DejaVu Sans Mono" "Book"

Bitstream Vera Sans Mono isn't installed by default. Installing bitstream-vera-sans-mono-fonts.noarch doesn't change the default monospace mapping

**Comment by robmv** [comment]
Tested forcing Firefox Monospace mapping to Bitstream Vera Sans Mono, no change :-(

![fonts](https://cloud.githubusercontent.com/assets/1652983/15636549/9b55fabc-25cc-11e6-993f-d08e0092a5c1.png)

**Comment by robmv** [comment]
Another test, this time I find this weird: If the font-family is only `monospace, 'Powerline Symbols'` it display correctly but `'Bitstream Vera Sans Mono', monospace, 'Powerline Symbols'` not. Without Bitstream Vera Sans Mono installed both map to the default monospace

    # fc-match "monospace"
    DejaVuSansMono.ttf: "DejaVu Sans Mono" "Book"

    # fc-match "Bitstream Vera Sans Mono"
    DejaVuSansMono.ttf: "DejaVu Sans Mono" "Book"

**Comment by sickill** [comment]
That is weird indeed... Looks like a bug outside of asciinema player in my opinion.

**Comment by sickill** [comment]
Is this still an issue for you @robmv ?

**Comment by robmv** [comment]
Yes, but I think it is fair to close the issue. I have been unable to detect what is making Firefox to make sometimes bad fonts calculations. On Twitter, generated cards for websites show truncated titles and summary. Still investigating but I am sure is a Firefox issue and not asciinema related.

**Comment by sickill** [comment]
Ok, thanks!

**Comment by shivams** [comment]
@robmv I have filed a bug-report on Mozilla for the same: https://bugzilla.mozilla.org/show_bug.cgi?id=1636690

Do you have some leads about the cause of the issue? The issue is certainly there, but it's getting difficult to reproduce it in fresh environments.
