### ISSUE TITLE
24-bit color support

### ISSUE THREAD

**Issue by gdamore** [asciinema/asciinema-player#29]
It would be really excellent if asciinema understood the 24-bit color extension, which is supported by XTerm and a number of other terminal emulators like iTerm2.

The 24-bit color uses these extensions to the SGR command:

To set foreground: CSI 38 ; 2 ; <r> ; <g> ; <b> m
To set background: CSI 48 ; 2 ; <r> ; <b> ; <b> m

In the above, <r> <g> and <b> are 8-bit values for red green and blue channels, printed e.g. via %d.
For example, here are corresponding Go strings for this, as I use them in Tcell - these are terminfo strings that can be displayed via tparam() using r, g, b values as the 3 parameters:

"\x1b[38;2;%p1%d;%p2%d;%p3%dm"
"\x1b[48;2;%p1%d;%p2%d;%p3%dm"

While terminfo doesn't have capabilities for this, I do have support for them in my tcell terminal handling package (see https://github.com/gdamore/tcell ), which allows users/programmers to get the actual intended colors instead of whatever theme overrides may be present.  This is mostly useful for displaying images, or in terminal based games (see https://github.com/gdamore/proxima5 for what I am talking about.)

**Comment by sickill** [comment]
Thanks for suggestion. I started work on this in #30.

**Comment by gdamore** [comment]
Cool !  Thanks!

**Comment by sickill** [comment]
@gdamore https://asciinema.org/a/46488

Could you try recording some true color demos (tcell, proxima5 etc) ?

**Comment by gdamore** [comment]
Yeah sure.  Give me a few. :-)

**Comment by gdamore** [comment]
https://asciinema.org/a/eahnoti2srkdnk2uobps4101y

**Comment by sickill** [comment]
Awesome! I just made it a "featured recording" ;)
