### ISSUE TITLE
Change speed of embeded script

### ISSUE THREAD

**Issue by Angristan** [asciinema/asciinema-player#32]
Hello, 

is it possible to change the speed of the player with the embeded version ?

I saw someone adding `data-speed="2"` but it does not work for me.

**Comment by sickill** [comment]
This should work... are you 100% sure it doesn't?

**Comment by Angristan** [comment]
Oh, yeah, today it's working ^^

What about the height ? data-height ?

**Comment by sickill** [comment]
The height is automatically adjusted to the size of the terminal at the time of recording.
All other params are documented here: https://asciinema.org/docs/embedding

**Comment by Angristan** [comment]
So it's not possible to modify it ? I don't see it on https://asciinema.org/docs/embedding

**Comment by sickill** [comment]
Correct, not possible.

**Comment by Angristan** [comment]
Ok, that's not very convenient because asciinema resizes the termnial automatically, and if you try to resize when recording it crashes :/

**Comment by sickill** [comment]
@Angristan If it crashes when resizing a terminal during recording than it's a bug. Could you open an issue for this, with details like asciinema version, your OS version?

**Comment by Angristan** [comment]
Done : https://github.com/asciinema/asciinema-player/issues/33
