### ISSUE TITLE
crash when recording and resizing the terminal window

### ISSUE THREAD

**Issue by Angristan** [asciinema/asciinema-player#33]
Hello,

I'm using asciinema 0.9.8-1 (from debian repo) on my Debian 8 server, and I access it via Putty on Windows 10.

When I start the record, no problem : 

![screenshot_23-06-2016_o46rgxfj](https://cloud.githubusercontent.com/assets/11699655/16310606/7c9a0f78-396d-11e6-9a8f-9327669b1590.png)

But if I resize during the record, asciinema crashes and I have a lot of Python errors : 

![screenshot_23-06-2016_k7urbsr1](https://cloud.githubusercontent.com/assets/11699655/16310626/8f6ae802-396d-11e6-949e-834e20cb0aab.png)

**Comment by sickill** [comment]
Looks like this is a bug occurring only under Python 3 (which I can see in your stack trace).

**Comment by Angristan** [comment]
Do I have to use Python 2 ? If yes, how ?

**Comment by sickill** [comment]
You don't have to, Python 3 is supported, but if you want to avoid this bug you can try Python 2. I don't really know how to do it under Debian (it seems to be packaged for Python 3).

**Comment by Angristan** [comment]
And we can't fix this bug instead ? :tongue:

**Comment by sickill** [comment]
This bug is fixed now, new 1.3 release includes this bugfix.

**Comment by kk11kk11** [comment]
I running  putty  on windows10  & i want  use asciinema with putty  any  way  to  configure it on windows10  with putty , it will  save every  hit & ouput on terminal  in jpg format

**Comment by kk11kk11** [comment]
& what pre-requiste for asciinema on windows 10
