### ISSUE TITLE
Seek programatically

### ISSUE THREAD

**Issue by Nateowami** [asciinema/asciinema-player#35]
Currently the only way to control the player is via the user interface.

However, it's possible to play and pause programatically like so:

``` javascript
var click = new MouseEvent("click", {
    "view": window,
    "bubbles": true,
    "cancelable": false
});
document.getElementsByClassName("playback-button")[0].dispatchEvent(click);
```

It's also possible to get the progress:  

``` javascript
document.getElementsByClassName("gutter")[0].children[0].style.width
```

You can also detect whether it's playing with:

``` javascript
// Differentiates between a play and pause button. The play button has one triangle, while
// the pause button consists of two lines. Hence, when playing, the pause button is shown,
// and children.length is 2. 
document.getElementsByClassName("playback-button")[0].children[0].children.length == 2
```

However, I can't find a method to make the video seek. I know you can press <kbd>0</kbd> through <kbd>9</kbd> on the keyboard, but I'm looking for finer (and programmatic) control, so that I can implement my own controls and hide the current ones with `display: none`.

Is there any way to do this? I'd be happy to implement it myself, but I'm completely lost in Clojure. I honestly don't think it would be that hard to implement, since there is already a seek function; it just needs to be exposed to the API.

Any opinions about that? I saw a reference to the current version being a "rewrite." Was the former version written in JavaScript and stable enough that I could use it?

This is related to #12 is but not exactly the same.

EDIT: Just saw the wiki and it basically lists the methods I just listed, while mentioning that there was no formal API for this. Just hoping there's a workaround for seeking.

**Comment by sickill** [comment]
You could try to dispatch similar click event to the progress bar element, which calculates the seek position from event's mouse position. Not sure how hard it would be though.

There's a plan for official programmatic control API, it's most probably be based on the work in #18.

**Comment by Nateowami** [comment]
Thanks. I thought of that and might give it a try.

Just for anyone else who tries it: It appears that it's listening for `mousedown`, not `click`. Also, I believe the element with the listener is `span.bar`.

Any guess as to whether this is likely to be done in the near future? If you think it will be, I'll probably just wait. Otherwise I may implement something, but it'll be very hackish. If I do I may publish it as `asciinema-player-api-shim` or something. But it'll be next to worthless when a better API comes out, so if you think it may happen soon, I can wait.

**Comment by sickill** [comment]
I see your point. I can't really give any estimate on when it may be ready. I have a feeling this may not be sooner than in couple of months so if you need it working now then you can try "the hacky way" (I think it may not be that much of work).

I'm also happy to accept a PR with the proper controlling API (after some high level discussion of the API surface and how I see it exposed in the mentioned HTML5 element).

**Comment by Nateowami** [comment]
OK, thanks, makes sense.
I'd love to contribute but I have zero knowledge of ClojureScript (and too busy/lazy to learn it at this time).
If I get something working I'll let you know.

**Comment by sickill** [comment]
`currentTime` property has been now added to the DOM element: https://github.com/asciinema/asciinema-player#controlling-the-player-programmatically
It will be part of the next release.
