### ISSUE TITLE
can I hidden the control-bar?

### ISSUE THREAD

**Issue by Qquanwei** [asciinema/asciinema-player#38]

**Comment by Nateowami** [comment]
Hiding it with CSS is straightforward:
``` css
.control-bar {
    display: none;
}
```
Then you can make it autoplay, and it can still be control via the keyboard (numbers 0 to 9 for seeking, space bar for play/pause). See https://asciinema.org/docs/embedding for the configuration options the player supports out of the box.

**Comment by Qquanwei** [comment]
thanks . I think this configurable will be better :)

**Comment by sickill** [comment]
No plans for configuration option for this at the moment but @Nateowami suggestion should give you what you want as of now.

**Comment by bastienbeurier** [comment]
This CSS doesn't seem to work for me. Are you sure this still works? Is there another way?

**Comment by ku1ik** [comment]
The control bar can be hidden with `controls: false` option. This option has been added in v3.4.0.

**Comment by bastienbeurier** [comment]
Mhmmm I tried:
```
<script id="..." src="..." controls=0>
</script>gene
```

and 

```
<script id="..." src="..." data-controls=0>
</script>gene
```

And it didn't work. Am I missing something?

**Comment by Qquanwei** [comment]
> Mhmmm I tried:
> 
> ```
> <script id="..." src="..." controls=0>
> </script>gene
> ```
> 
> and
> 
> ```
> <script id="..." src="..." data-controls=0>
> </script>gene
> ```
> 
> And it didn't work. Am I missing something?

hi ,  i think controls option should as player props . `script` element does not support any other property.

```html
  <script src="/asciinema-player.min.js"></script>
  <script>
    AsciinemaPlayer.create('/demo.cast', document.getElementById('demo'), {
    controls: false
  });
  </script>
```
