### ISSUE TITLE
--max-wait

### ISSUE THREAD

**Issue by GodloveD** [asciinema/asciinema-player#40]
The `asciinema play` command has a `--max-wait` option that is very helpful.  Could this be implemented in the web player without too much trouble?

**Comment by sickill** [comment]
Yes. In fact version 1.x of the player supported this but it got lost during the 2.0 rewrite.

I'll see what we can do here 😎

**Comment by sickill** [comment]
It has been implemented in 1cc8c35ded38c04749534c6bdd3d4e8e6e4634b2. Will be released in the next version of the player.

**Comment by GodloveD** [comment]
Groovy!
