### ISSUE TITLE
Make code for embedded video compatible with LibreJS

### ISSUE THREAD

**Issue by jorgesumle** [asciinema/asciinema-player#41]
Embedded videos are detected as non-free JS code by LibreJS. 

<pre><samp>This script is detected as nonfree, external, and as defining functions or methods
https://asciinema.org/a/89325.js</samp></pre>

https://github.com/asciinema/asciinema-player/blob/master/LICENSE#L623
https://www.gnu.org/philosophy/javascript-trap.html
https://www.gnu.org/software/librejs/free-your-javascript.html

**Comment by sickill** [comment]
The script URL https://asciinema.org/a/89325.js is part of the [asciinema-server](https://github.com/asciinema/asciinema-server) project, and can be found here: https://github.com/asciinema/asciinema-server/blob/develop/assets/static/js/embed.js

Feel free to reopen in the server's repo.
