### ISSUE TITLE
Player very slow, crashes on large, fast-output, multicolor terminal output

### ISSUE THREAD

**Issue by lschumm** [asciinema/asciinema-player#42]
The Issue
----------

When you try to view a recoding large, fast-output terminal session, for example, `top | lolcat` (top doesn't know that the output is not a terminal, and thus prints a bunch of updates really fast), the site starts to lag and sometimes become unresponsive.

Examples
----------

- Piping top to lolcat https://asciinema.org/a/f55bkam3wekhqfte98j4heljy
- `cat`ing a bunch of sites through lolcat https://asciinema.org/a/1ct69s5n1rv7mct7ljbjiy6s0

System Info
------------

- MacBook Air (4GB RAM, Core i5), Mid '16, OS X Sierra 10.11, Safari Version 10.0.1 (12602.2.14.0.7), Google Chrome 53.0.2785.89 (64-bit)

**Comment by sickill** [comment]
We made some performance improvements recently. Isn't any better now?

**Comment by sickill** [comment]
I'm closing old issues. Please reopen if this is still a problem for you or if you can provide more details.
