### ISSUE TITLE
Maximum screen width?

### ISSUE THREAD

**Issue by wizzup** [asciinema/asciinema-player#44]
The record file play without any problem on my computer but was cropped on asciinema site

![2017-01-10-154206_1600x263_scrot](https://cloud.githubusercontent.com/assets/342500/21799347/70384eee-d74b-11e6-9e7d-ad91938a7272.png)

Mozilla Firefox 50.1.0

![2017-01-10-154515_1144x168_scrot](https://cloud.githubusercontent.com/assets/342500/21799431/cf756bc6-d74b-11e6-9c7d-b65ee0acb277.png)

Google Chrome 54.0.2840.59

![2017-01-10-155623_1231x196_scrot](https://cloud.githubusercontent.com/assets/342500/21799813/6611e5ea-d74d-11e6-8653-b572f5313e70.png)

Arch linux , asciinema 1.3.0 and termite v12

[widthtest.zip](https://github.com/asciinema/asciinema-player/files/695627/widthtest.zip)

https://asciinema.org/a/98762

**Comment by sickill** [comment]
It's not a bug, it's a feature ;) Just kidding.

The player on asciinema.org is put inside a `<div>` container, which is centered and has max width. Everything that doesn't fit in this container gets clipped. We do this so it aligns nicely with the rest of the content on the page.

One way of solving it would be to align the player to the left edge of the browser window. It would probably not look in majority of cases where the recordings are narrower though.

Or, better, to make the container `<div>` full-width, so when the automatically expands on both left and right when it's wider than the main-content-container in the layout.

**Comment by renannprado** [comment]
I changed the `.container` to `max-width: 100%` and it worked pretty nicely to me.
Though I think that class is outside of this project.

![image](https://cloud.githubusercontent.com/assets/2359543/25783779/463acab0-3338-11e7-9ce2-79aa1e0a5d1c.png)

**Comment by cesarizu** [comment]
I'm having the same issue.

I see that the `.asciinema-terminal` pre tag has the right size (i.e. `width: 128ch` for a 128x36 asciicast) but the some of the content is hidden to the right. Making it wider shows all the content. I see this happening with all casts (not only mine).

I wonder if it's a bug with my browser maybe? (Firefox 52.1.1 (64-bit) on linux)

**Comment by sickill** [comment]
The fix happened to be trivial 🎉
