### ISSUE TITLE
not playing well with mkdocs themes

### ISSUE THREAD

**Issue by anantshri** [asciinema/asciinema-player#46]
The mkdocs theme has a require.js which seems to get conky when this javascript from release is added.
https://github.com/mkdocs/mkdocs-bootstrap/
https://github.com/anantshri/mkdocs-reloaded/

I assume this javascript is a combination of multiple smaller script. Any chance we can get individual files and then i can try to debug the issue out.

**Comment by sickill** [comment]
All .js files from this directory are prepended to asciinema-player js code during the build. You can try using mkdocs with various combinations of these (**without** asciinema-player.js release build on a page) to see if it's any of these that's causing a problem.

**Comment by anantshri** [comment]
not well versed with the jvascript build frameworks. any place i can find all javascript individually?

**Comment by sickill** [comment]
Ah, sorry, I forgot to tell which directory contains these individual files. They're here: https://github.com/asciinema/asciinema-player/tree/master/resources/public

**Comment by anantshri** [comment]
this is solved. @sickill thanks for the hint about files.
