### ISSUE TITLE
asciinema-player.js size is large and growing

### ISSUE THREAD

**Issue by crawshaw** [asciinema/asciinema-player#49]
`asciinema-player.js` is a large and growing binary:

Release          | Size
-----------------|------- 
v2.0.0, Jan 2016 | 445 KB
v2.1.0, Mar 2016 | 471 KB
v2.2.0, Apr 2016 | 501 KB
v2.3.0, Oct 2016 | 582 KB
v2.3.1, Nov 2016 | 618 KB
v2.4.0, Dec 2016 | 630 KB

Unfortunately, increasing download size means that using the latest version is not always obvious. I have one use in mind that appears to be met by all the features in v2.0.0, so working out how to use the old version has value because it makes my page ~30% smaller.

(As an aside, this is a great project and I really appreciate all the work going on. Thank you for all your effort!)

**Comment by sickill** [comment]
This is something I noticed already and I'm not very happy about it too. It's ~0.5 MB, and that's because it's compiled from ClojureScript and the resulting .js file includes some part of ClojureScript standard library. There's handful of external libraries used in the player, but I try to limit this (this commit decreased the size of the bundle by ~100kb recently: https://github.com/asciinema/asciinema-player/commit/6f9ca319b883a97fbf87117ff8a0426a5a7d3bca) so we don't increase the file size too much.

The latest ClojureScript compiler (released yesterday) can do dead-code-elimination on js modules (es6, commonjs, npm) so there's a chance it will decrease the resulting file size by removing (at least some) parts of React that are not used in the player.

One thing which helps is serving asciinema-player.js gzipped (`Content-Encoding: gzip`), which reduces date transfer by a great amount.

**Comment by sickill** [comment]
If you configure Nginx/Apache/other to send `.js` files gzipped (with `Content-Encoding: gzip`) than it's not that bad (latest version gzipped is 140 KB).

**Comment by sickill** [comment]
I don't have a definitive solution for this and nobody else found this to be a big problem so I'm closing it for now.

**Comment by sickill** [comment]
Re-opening in hope someone may have some ideas on how to reduce the size of built artifact.

**Comment by sickill** [comment]
We use ClojureScript compilation in advanced mode and we elide all asserts from the resulting code: https://github.com/asciinema/asciinema-player/blob/master/project.clj#L80-L82

However, there are several major libs that add up, making it 600kb+ js file:

- ClojureScript standard library
- React.js
- reagent
- core.async

I suspect React+reagent are the heaviest here. Player's UI is quite simple so maybe it would be worth investigating React-like libs that are more light-weight, with less features (either in pure CLJS or wrappers over JS lib). In the extreme case we could consider rewriting the rendering part to do manual DOM manipulation without virtual DOM abstraction.

Anyway, it would be nice to see how much each of these contributes to the final file size in the first place.

**Comment by sickill** [comment]
Replacing React with [Preact](https://github.com/developit/preact) seems to shave off about 113kb: https://github.com/reagent-project/reagent/issues/271#issuecomment-266263892

**Comment by developit** [comment]
Feel free to ping me if you need help with anything relating to Preact. Myself or someone else is always available on [Slack](https://preact-slack.now.sh).

**Comment by sickill** [comment]
@developit awesome, thx!

**Comment by anmonteiro** [comment]
FWIW I've found that [`source-map-explorer`](https://github.com/danvk/source-map-explorer) works great for ClojureScript builds.

**Comment by piotrts** [comment]
Hi. You should be able to decrease js file size a bit by setting `:fn-invoke-direct` cljs compiler option to `true`. I haven't tested that though.

**Comment by anmonteiro** [comment]
`:fn-invoke-direct` is about runtime performance, not code size. It's also behind a flag because it's experimental and stuff might break. Use with caution.

**Comment by piotrts** [comment]
Right. But it also results in a bit smaller code size, that's why I suggested it here.

**Comment by sickill** [comment]
I tried `:fn-invoke-direct true`, it produced 5kb smaller output, so that's accidental. Thanks for bringing it up though, it may be useful to improve player's performance.

**Comment by sickill** [comment]
I modified VT parser to build its lookup table at runtime instead of compile time and this trimmed down 100kb 🎉

**Comment by sickill** [comment]
I used source-map-explorer and it generated this: https://www.dropbox.com/s/kv1bubrrjtgkx1j/source-map-explorer.png?dl=0

Interesting thing is that `asciinema.player.messages.cljs` compiles to 36 kb, while it's only 2 simple `defprotocol` definitions and a few `defrecords`: https://github.com/asciinema/asciinema-player/blob/master/src/asciinema/player/messages.cljs

Compared to `asciinema.player.view` or `asciinema.vt` namespaces which have relatively way more code in them `messages.cljs` is suspiciously big.

**Comment by sickill** [comment]
Another interesting thing is that `schema.core` takes 21 kb, even with `:elide-asserts true` (which removes all asserts, including all schema validations from the built artifact). `schema` is only used in dev/test and is not used by release code. It seems that requiring it or defining top-level forms like [this](https://github.com/asciinema/asciinema-player/blob/master/src/asciinema/player/format/asciicast_v1.cljs#L8) adds it to the output.

**Comment by sickill** [comment]
I've just released v2.5.0 which is 571 KB - https://github.com/asciinema/asciinema-player/releases/tag/v2.5.0

Not a dramatic difference when compared to the last version but it's a good direction at least 😅

**Comment by dupuchba** [comment]
@sickill have you understood why `messages.cljs` was so big compared to code size ? thanks a lot for this useful thread :-)

**Comment by sickill** [comment]
The player [has been rewritten in JS+Rust](https://blog.asciinema.org/post/smaller-faster/), reducing the bundle size 4x.
