### ISSUE TITLE
Embeddable discovery

### ISSUE THREAD

**Issue by lucasmichot** [asciinema/asciinema-player#5]
Asciicinema is a great tool !
Any chance to implement some embed tags or metadata so that the player can be embeddable in slack, instead of jus a link ?
=> https://api.slack.com/robots

**Comment by sickill** [comment]
Yeah, that's neat idea. I plan to add discovery tags for oEmbed/Twitter Card/Open Graph. 
This one belongs more to https://github.com/asciinema/asciinema.org/ repo so I'm closing this one.

**Comment by sickill** [comment]
@lucasmichot discovery has just been added: http://blog.asciinema.org/post/embedding/
