### ISSUE TITLE
Theme pull request

### ISSUE THREAD

**Issue by probandula** [asciinema/asciinema-player#50]
Hello asciinema-team,
I wanted to use my own theme in the asciinema player. I tested it and it seems really easy to import another .less file from the themes. Is there a possibility to bring a own theme to the official repository, or maybe even a possibility to easily create a custom theme without recompiling the less every time something changes (maybe a simple `asciinema-theme.css` which could be added)? If it's possible to contribute with a theme, I'd like to send a pull request of my finally published [default terminal theme](https://github.com/probandula/enize-theme).
Thank you in advance, nice work, really like asciinema :)

**Comment by sickill** [comment]
It's very easy to use additional .css file with asciinema player.
This is a CSS for monokai theme which is bundled with the player: https://gist.github.com/sickill/afeb74c67f3b23a00bd97ce6b744f486

If you want to use a custom theme then just make a new .css file based on the above one, replacing `.asciinema-theme-monokai` with `.asciinema-theme-foobar` and use `<asciinema-player ..... theme="foobar"></asciinema-player>`.

**Comment by probandula** [comment]
Thanks a lot, that's what I was searching for. I just thought, the generated css would be more complex.
Thanks and have a good time :)

**Comment by sickill** [comment]
I turned this into a wiki page: https://github.com/asciinema/asciinema-player/wiki/Custom-terminal-themes

**Comment by probandula** [comment]
Nice work, thanks
