### ISSUE TITLE
& functions lead to other videos as intented

### ISSUE THREAD

**Issue by ShalokShalom** [asciinema/asciinema-player#51]
This is my video: https://asciinema.org/a/9vzt60y52krsjye6m9ol6w81t

add &theme=solarized-dark and you get to a different one: 
https://asciinema.org/a/9vzt60y52krsjye6m9ol6w81t&theme=solarized-dark

Same as with &speed=2 as well, while ?t=25 work correctly

**Comment by sickill** [comment]
I've migrated this issue to proper repo. Thanks!
