### ISSUE TITLE
Add a way to use asciinema-player with a package manager

### ISSUE THREAD

**Issue by aloupfor** [asciinema/asciinema-player#54]
Is there a way to use a package manager (such as bower) for asciinema-player to keep an updated version and avoid versioning a vendor?

**Comment by sickill** [comment]
We don't have that at the moment, but it's a good idea.
Maybe npm package would be the best?

**Comment by aloupfor** [comment]
I can't say what is the best option. Some rather have both bower (handling front dependencies) and npm (handling back dependencies) while others rather have only npm (handling back and front dependencies).

I think that nothing prevents asciinema-player to provide a bower package and a npm package at the same time.

**Comment by derhuerst** [comment]
Having it on npm would be a great benefit! I'm about to write and Asciicast renderer, and, not being fluent in ClojureScript, having difficulties to interface with the parsing part of the player. I have two choices right now:

- download the player on the fly, and expose parts of it through a wrapper, transpile everything to JS
- download the fully built JS of the player and poke around in it to find the relevant part

Both of these choices kill my productivity as a non-ClojureScript dev. What I would love to have is the following:

```shell
npm install asciicast-parser
```

```js
const parser = require('asciicast-parser')

const parse = parser({width: 80, height: 20, …})
parse('\u001b[1;31mHello ') // -> frame of text
parse('\u001b[32mWorld!\u001b[0m\n') // -> frame of text
```

Another npm would be `asciinema-renderer`, which would render these to the DOM.

**Comment by derhuerst** [comment]
FYI Solved it using [`headless-terminal`](https://github.com/dtinth/headless-terminal#usage): https://github.com/derhuerst/asciicast-to-svg/blob/6dea5df/index.js#L44-L69

**Comment by sickill** [comment]
I like what datascript guys are doing here: https://github.com/tonsky/datascript/tree/master/release-js

They wrap the ClojureScript compiled .js file with `wrapper.prefix` and `wrapper.suffix` producing a universal script that can be used with NPM/CommonJS/browser/whatever, and they also release it to npmjs.org.

**Comment by SkypLabs** [comment]
Wouldn't it be easier to add a `bower.json` file and a `package.json` file to this project? That way, it would be possible to install the asciinema player using `bower`, `yarn` and `npm`.

I can submit a pull request if you agree with me.

**Comment by sickill** [comment]
I don't really understand how bower works... I always thought it's only for fetching libs.
Would it allow importing/requiring the player from ES6/CommonJS modules?

**Comment by derhuerst** [comment]
FYI My/our need for the `asciicast-parser` npm package still exists. I'm willing to help on this, but I'm not familiar with ClojureScript tooling.

[Bower has proposed to switch to yarn/npm for package management](https://bower.io/blog/2017/how-to-migrate-away-from-bower/).

**Comment by SkypLabs** [comment]
@sickill:

> I don't really understand how bower works... I always thought it's only for fetching libs.

Actually it is the case. It is a package manager for JS and CSS files (typically, the `asciinema-player.css` and `asciinema-player.js` files).

> Would it allow importing/requiring the player from ES6/CommonJS modules?

I am not sure to understand. Can you precise your thoughts?

@derhuerst:

> FYI My/our need for the `asciicast-parser` npm package still exists. I'm willing to help on this, but I'm not familiar with ClojureScript tooling.

Same! I really want to be able to install the `asciicast-player` using `yarn`.

> [Bower has proposed to switch to yarn/npm for package management](https://bower.io/blog/2017/how-to-migrate-away-from-bower/).

Yes `yarn` is way better than `bower` and it uses the same `package.json` file as `npm`.
