### ISSUE TITLE
Missing unicode characters in thumbnail

### ISSUE THREAD

**Issue by cjwelborn** [asciinema/asciinema-player#59]
I've noticed that in preview thumbnails, certain unicode characters are either rendered as the "missing glyph", or not rendered at all.

This is a screenshot of [this asciinema cast](https://asciinema.org/a/112299), with the characters rendered:

![whichfile-asciinema-arrow-char](https://cloud.githubusercontent.com/assets/3335984/24888472/6a784b92-1e29-11e7-8383-25626449c23b.png)

This is the [preview thumbnail](https://asciinema.org/a/112299.png), with those same characters missing:

![image](https://cloud.githubusercontent.com/assets/3335984/24888490/82abc1bc-1e29-11e7-8b99-964fb7743f7c.png)

Character: ⯈

Name: `BLACK MEDIUM RIGHT-POINTING TRIANGLE CENTRED`

Hex: `0x2bc8`

As mentioned before, I've also seen them rendered as the "missing block glyph". This is my profile page on mobile:

![image](https://cloud.githubusercontent.com/assets/3335984/24909020/ef1c213a-1e87-11e7-9fff-90f8361b96fb.png)

They seem to render fine for the previews found in [my profile](https://asciinema.org/~cjwelborn) on the desktop.

**Comment by cjwelborn** [comment]
Are previews generated client side? That would explain the mobile issue. I'm just trying to figure out what's going on.

**Comment by sickill** [comment]
The previews are generated server-side, as text, and displayed as html with monospaced font in the browser.

**Comment by sickill** [comment]
Linking this tweet as it may be helpful: https://twitter.com/FakeUnicode/status/851548528337756160

**Comment by cjwelborn** [comment]
Okay, so forget about the mobile thing. Previews are rendered with whatever characters and fallback-fonts the client system can handle.

That still leaves the thumbnails though. I don't know how `asciinema` is set up, but my guess is the fonts/fallback-fonts are missing from whatever machine generates the PNG images.

**Comment by sickill** [comment]
Yes, I'm pretty sure we're missing some font package there. The PNG is generated with [a2png](https://github.com/asciinema/a2png), and the (Ubuntu( system it's running on has only `ttf-bitstream-vera` explicitly installed. I wonder what package includes the font(s) covering these triangles etc...

**Comment by sickill** [comment]
@cjwelborn what browser and OS you used to make the first screenshow (where it's properly displayed)?

**Comment by cjwelborn** [comment]
@sickill, kubuntu 16.10, and whatever the latest Chrome is. I upgraded kubuntu since then (17.04), but I'm unable to re-test for a few weeks.

**Comment by sickill** [comment]
It's been a while, and the PNG preview generation has been rewritten since. Also, the recommended and default preview image is now SVG. Given that I'll go ahead and close this, but feel free to reopen if notice anything strange with the SVGs or new PNGs.
