### ISSUE TITLE
Auto-pause when window/tab loses focus

### ISSUE THREAD

**Issue by sickill** [asciinema/asciinema-player#6]
This would be nice addition. Some examples on how to achieve this: http://www.smashingmagazine.com/2015/01/20/creating-sites-with-the-page-visibility-api/?utm_source=html5weekly&utm_medium=email

**Comment by marcellodesales** [comment]
+1 on that!

**Comment by sickill** [comment]
This could prevent playback start for autoplay URLs when you open them in a new tab.

**Comment by sickill** [comment]
Given the player has control API now this visibility watching could be implemented where the player is used, so in asciinema.org website codebase.
