### ISSUE TITLE
Changing playback speed in the player doesn't work for me

### ISSUE THREAD

**Issue by jandubois** [asciinema/asciinema-player#60]
Using both Chrome and Safari on macOS Sierra, pressing the `<` and `>` keys doesn't change the playback speed.

Appending `?speed=0.5` to the URL does slow down the playback, so the problem seems to be with the key code logic. Other keys, like `f`, ` ` (space), or `0` to `9` do work though.

Looking at the code, I wonder if the issue is related to the fact that `<` and `>` require pressing the Shift key, and the code is inside a `(when-not (has-modifiers? dom-event)` condition:

https://github.com/asciinema/asciinema-player/blob/7b9acc9/src/asciinema/player/view.cljs#L248

**Comment by sickill** [comment]
Yeah, looks like e3a42dd4b4a95593dbf1040101e4e7b022b2df30 broke this.

**Comment by jandubois** [comment]
Maybe just remove `shiftKey` from the list of modifiers? It would "trap" Shift-Space, but all other characters can't be typed with the Shift key down anyways, so it seems a reasonable compromise, given that Shift-Space is unlikely to have any special meaning in a browser.

**Comment by sickill** [comment]
Shift-space does scroll up in Chrome (and I'm pretty sure in other browsers too). But I have an idea, hold on.

**Comment by jandubois** [comment]
Thanks! Any idea when it will be deployed on https://asciinema.org/ ?

At least I assume it hasn't been deployed yet, as it doesn't seem to work for me.

**Comment by sickill** [comment]
@jandubois it's deployed now.

**Comment by jandubois** [comment]
> it's deployed now.

Thank you, works great!

**Comment by fazlerabbi37** [comment]
@ku1ik I think these two keyboard shortcuts are missing from the docs here: https://docs.asciinema.org/manual/player/shortcuts/. :sweat_smile: 

I came to open an issue about keyboard shortcuts for speed up and down and found this issue.

If that is the correct place for adding these two, then I can quickly add an MR in the docs repo: https://github.com/asciinema/asciinema.github.io

**Comment by thisago** [comment]
It seems that a keyboard shortcut for change playback speed is missing on the new player version.

https://github.com/asciinema/asciinema-player/blob/8b1550ac4d87b37c011281e2974d58b1edf55615/src/components/Player.js#L318-L358
