### ISSUE TITLE
Dispatch "tick" event each time `currentTime` changes

### ISSUE THREAD

**Issue by cemerick** [asciinema/asciinema-player#65]
My use case is: I'd like to tie the state of other presentation elements to particular "timecodes" within a terminal presentation. For example, showing particular captions for different parts of the presentation, display a coordinated slideshow, and so on.

I can do this now by brute force, i.e. polling `player.currentTime` every second and dispatching my own event for interested parties to receive:

```js
var player = document.getElementById("player");
var playing = false;
var tick = function () {
  if (playing) {
    player.dispatchEvent(new Event("tick"));
    setTimeout(tick, 1000);
  }
}
player.addEventListener("play", function () { playing = true; tick(); });
player.addEventListener("pause", function () { playing = false; });
player.addEventListener("tick", function () { console.log(this.currentTime); });
```

This works, but is gnarly. Also, user expectations can't be met when seeking to another place in the presentation while paused (a minor detail maybe, but there it is).

If the player were to dispatch a `"tick"` event on each change to the `currentTime` property, this would tidy up this use case nicely.

**Comment by sickill** [comment]
Hey @cemerick! Yeah, that sounds like a nice addition and seems quite straightforward to add.

**Comment by hihihippp** [comment]
I propose to add an event listener: timeupdate, like play pause event now in asciinema and html5 video player. 
it provide the potential power:
1. add ab-loop
2. add subtitle
3. sync to any html5 element in web page

**Comment by sickill** [comment]
Closing as it's the same as new #184 but this one was opened back when the player was still implemented in ClojureScript.
