### ISSUE TITLE
terminal size change causes incorrect wrapping (or absence of such, no new line added)

### ISSUE THREAD

**Issue by yarikoptic** [asciinema/asciinema-player#69]
I was excited to see https://github.com/asciinema/asciinema-player/commit/430b7f8c292d7e42173ee96d7f0fd86a19ed79c8 in action but then spotted that some output is not wrapped correctly if cols value differs from the original, e.g. compare those shell comments wrapping 
on
https://asciinema.org/a/134832?poster=npt:225
vs
https://asciinema.org/a/134832?poster=npt:225&cols=81

**Comment by sickill** [comment]
Looks like a bug, yeah. I'm trying to reproduce it on a simpler case but no luck so far.

**Comment by sickill** [comment]
Not a bug actually :)

If you download this asciicast () and open it (for ex. in `less`), search for `0.021936`. This is where carriage return (`\r`) was printed. It seems this was auto-typed using some tool during the recording, and this tool made use of terminal width which was 80 then. It artificially added `\r`, which does no harm when printed "on the edge of the screen", but causes this problem when printed before the edge. When you make the player 81 columns you move the edge 1 column right, but this `\r` is executed when cursor is 1 char left to the edge.

Anyway, this can't easily be solved by asciinema-player. It's not really player's fault (its virtual terminal emulator adheres to the ANSI standard here). We could try to add some workaround for special cases like this but I'm not sure it's worth it.

If you disagree (or have ideas for this) I'll re-open.

**Comment by sickill** [comment]
As a quick solution you can edit this json recording, find `\r` occurences like this one, delete them, and then re-upload this recording as new one.
