### ISSUE TITLE
ANSII escape codes are left unparsed for poster data:text/plain

### ISSUE THREAD

**Issue by aqw** [asciinema/asciinema-player#70]
`README.md` gives the following example for using arbitrary text as the poster/preview:

`<asciinema-player src="..." poster="data:text/plain,I'm regular \u001b[1;32mI'm bold green\u001b[3BI'm 3 lines down"></asciinema-player>`

What is printed as the poster, however, is the literal string. None of the escape codes are interpreted.

---Alex

**Comment by sickill** [comment]
@aqw what version of the player are you using?

**Comment by aqw** [comment]
@sickill Sorry for not including that information initially.

I am using the latest version (2.5.0) of asciinema-player.

---Alex

**Comment by sickill** [comment]
Hmm, does this happen for you on particular browser or on all? It seems escaping of unicode characters within element attributes is not being handled by the browsers...

🤔
