### ISSUE TITLE
tmux recording gets messed up

### ISSUE THREAD

**Issue by sickill** [asciinema/asciinema-player#76]
Reported by @madchap here: https://github.com/asciinema/asciinema/issues/237

Hi,

Great tool :)

I was trying from within a tmux, but as you see here, the output is a bit screwed up.
https://asciinema.org/a/139163

Any advices?

Thanks! I am spreading the word about this goodness ;-)
Best,
fred

**Comment by danielyli** [comment]
Friendly bump — to my dismay I found I can’t play back my tmux recordings properly. I’d gladly help, but alas I’m not a Closure or JS dev. Is this something that’s still on the radar?

**Comment by sudo-bmitch** [comment]
@danielyli I was following this since I experienced the issue before. Something in my Debian environment changed in the last year or so and I no longer see this behavior. Not sure what update fixed things (whether that's tmux, asciinema, the terminal, or something else).

**Comment by sickill** [comment]
The recording at https://asciinema.org/a/139163 does look alright to me now. Let me know if you still experience tmux related display issues. Otherwise I'll close this.

**Comment by sudo-bmitch** [comment]
I used to experience this and haven't seen it for quite some time. Not sure if it was an update to tmux or asciinema that fixed it for me.
