### ISSUE TITLE
Wiki's tutorial on how to edit the content played

### ISSUE THREAD

**Issue by hugolpz** [asciinema/asciinema-player#78]
It would be good to have a tutorial 

* [how to edit the content played](https://github.com/asciinema/asciinema-player/wiki/Edit_recording)

So after making a recording we may clean up the record from mistyping and errors, so to create clean, ultimate videos for the said action recorded.

**Comment by gmile** [comment]
@hugolpz I wanted an editing tutorial too, and found this one: https://asciinema.org/a/7445. Maybe it'll come in handy.

**Comment by cirocosta** [comment]
Hey, maybe you want to give [`asciinema-edit`]https://github.com/cirocosta/asciinema-edit() a try.

For instance, if you wanted to do what the person in the tutorial does you would:

1. open the cast and see which timestamps you'd want to remove.
2. knowing the timestamps: `asciinema-edit cut --start <timestamp_1> --end <timestamp_2> ./cast`

Then, if you want to remove the delays, you could make use of `asciinema-edit quantize`:

`asciinema-edit quantize --range 0.5 ./cast` (for every delay between 0.5 and up, cut the delay down to 0.5).  

*ps.: with `quantize` you could avoid the `cut` step entirely by opening the cast file in your editor, cutting the parts you want by just removing the lines and then apply a quantization on it to fix the timestamps*

*disclaimer: I wrote the tool*

**Comment by sickill** [comment]
Thanks for the tips on the topic 👍
