### ISSUE TITLE
Scrubber out of sync when setting playback speed > 1 on embedded

### ISSUE THREAD

**Issue by jtreminio** [asciinema/asciinema-player#8]
Code used:

    <script src="//asciinema.org/a/19251.js?" id="asciicast-19251" async data-speed="2"></script>

Clicking play and letting it run through at faster-than-1 speed results in scrubber stopping before it reaches end:

![image](https://cloud.githubusercontent.com/assets/589398/7350089/f022b542-ecc2-11e4-9ff8-d57baa1fb7c5.png)

Same issue can be seen if you click play and start clicking through scrubber timeline. You are unable to click past the point where it stops.

If you click to end of timeline right when the movie starts, the scrubber will keep moving right, but the movie won't actually play. Clicking to beginning of timeline does not start movie. A page reload is required.

![image](https://cloud.githubusercontent.com/assets/589398/7350172/6bbffa70-ecc3-11e4-843c-da24949b34ab.png)

**Comment by sickill** [comment]
This has been fixed in recent version of the player.
