### ISSUE TITLE
asciicast/load slow for casts with big dimensions

### ISSUE THREAD

**Issue by marionebl** [asciinema/asciinema-player#81]
Using `asciicast/load` via [load-asciicast](https://github.com/marionebl/load-asciicast) I noticed some asciicasts take very long to parse. Two examples users of [svg-term-cli](https://github.com/marionebl/svg-term-cli) raised, both with relatively high width/height properties.

| cast | width | height | size | render time | 
|-----|-------|--------|-----|------------|
| [156787](https://asciinema.org/a/eUnQPgWgKFVl4WUqinKbX7Qze) | 208 | 58 | 29K | 145s |  
| [156579](https://asciinema.org/a/znqFxSzM9CmIJINrmn2IzPX5g) | 155 | 43 | 59K | > 300s |

> Source: https://github.com/marionebl/svg-term-cli/issues/15

Forcing the screen buffer size down decreases parsing time:

| cast | width | height | size | render time | 
|-----|-------|--------|-----|------------|
| [156787](https://asciinema.org/a/eUnQPgWgKFVl4WUqinKbX7Qze) | 80 | 25 | 29K | 5s |  
| [156838](https://asciinema.org/a/D3qhyP1ORhqwL3yllRnnzHIbN) | 80 | 25 | 28K | 5s | 
| [156579](https://asciinema.org/a/znqFxSzM9CmIJINrmn2IzPX5g) | 80 | 25 | 59K | 11s |

**Comment by redaxmedia** [comment]
Could you please investigate into this issue?

**Comment by sickill** [comment]
This is interesting. I don't have a clue what's going on there. Thanks @marionebl for making awesome comparison table 👍  It will definitely help debugging this.

**Comment by timlindeberg** [comment]
I think it might be an issue with large files in general. It seems like asciicast/load uses a lot of memory. When trying to render this cast

https://asciinema.org/a/thqQQnk2QGEcx3N5hv9MGiSwl

which is 165K, loading the cast crashed with an out of heap memory exception after a while. Increasing the memory by running:

```
node --max-old-space-size=8096 ~/.nvm/versions/node/v8.9.4/bin/svg-term --in=trepl --out examples/trepl.svg --window
```

the process quickly consumed around 3 GB of ram and finished loading in a way shorter time. It seems that the default heap size is too small for loading these types of files (or asciicast/load uses too much memory :))

**Comment by SakiiR** [comment]
It is simply very long when you click in the progress bar. It would be great to improve this :)

**Comment by ngocdaothanh** [comment]
`asciicast/load` loads all the screencast to memory, causing out of memory problem:
https://github.com/marionebl/svg-term/issues/13

It's not good when over 2GB of memory is required for loading only 1.6MB of screencast.

asciinema v2 supports streaming.
Is there a method different from `asciicast/load` that gives each frame one by one?

**Comment by sickill** [comment]
This function uses a lot of mem in some cases indeed. It's from the old, no longer supported, version of the player though.

Better to just parse it in JS,it's actually very simple. For inspiration see driver/asciicast.js
