### ISSUE TITLE
Webplayers seems to be repeating the command on the next line

### ISSUE THREAD

**Issue by camponez** [asciinema/asciinema-player#82]
This json file was recored using asciinema (962dee94a00931ce6fae149dfe72e8809eade470)

[Json file](https://gateway.ipfs.io/ipfs/QmfNta939S2pWV374jQNKsJL1hnyozbEP4ez49Yk3gQTHD)

[Video using webplayer](https://gateway.ipfs.io/ipfs/QmcXpGCoD8VBcsXTaUJb17AQRkCNgtNrFcp9MjkeZJumVV/)

**Comment by GregoireHENRY** [comment]
did you solve this? I face the same issue

**Comment by sickill** [comment]
Those IPFS links don't work anymore so I can't reproduce the problem. I'm gonna close this, but if you still encounter this issue feel free to re-open.
