### ISSUE TITLE
Shortcute f for fullscreen in IE don't work.

### ISSUE THREAD

**Issue by ewmt8k** [asciinema/asciinema-player#83]
Is it possible that the shortcute f for fullscreen mode not work in IE?
The icon to click bottom left do work.

**Comment by sickill** [comment]
Which version of IE it doesn't work on?

**Comment by ewmt8k** [comment]
Hi ,

IE11

regards

Dirk

2018-02-04 10:18 GMT+01:00 Marcin Kulik <notifications@github.com>:

**Comment by sickill** [comment]
Closing as IE is dead now.
