### ISSUE TITLE
How do i provide the cast content inline?

### ISSUE THREAD

**Issue by jameshfisher** [asciinema/asciinema-player#86]
The README says I can embed a player like this:

```html
<asciinema-player src="/demo.cast"></asciinema-player>
```

However, I want to embed my cast file in the HTML like this:

```html
<asciinema-player>
{"version": 2, "width": 92, "height": 37, "timestamp": 1522359678, "env": {"SHELL": "/bin/bash", "TERM": "xterm-256color"}}
[0.237154, "o", "\u001b[?1034h\u001b[1m~\u001b[0m\r\r\n$ "]
[1.206609, "o", "e"]
[1.236777, "o", "c"]
[1.333918, "o", "h"]
[1.373743, "o", "o"]
[1.473761, "o", " "]
[1.669467, "o", "h"]
[1.783489, "o", "i"]
[2.058803, "o", "\b\u001b[K"]
[2.265758, "o", "e"]
[2.365743, "o", "l"]
[2.682537, "o", "l"]
[2.915974, "o", "o"]
[3.135463, "o", "\r\n"]
[3.135657, "o", "hello\r\n"]
[3.144096, "o", "\u001b[1m~\u001b[0m\r\r\n$ "]
[4.063228, "o", "exit\r\n"]
</asciinema-player>
```

Is this possible? What is the API for doing so?

**Comment by jameshfisher** [comment]
For context: I would prefer that each of my blog posts is a self-contained file, rather than multiple files with links between them which can break and which add latency when loading the page.

**Comment by jorgesumle** [comment]
No, it's not possible to do it like you say. The `src` is where you should put the recording, not in the tag content. The tag content is to display content when the recording cannot be player (because the HTML element is not recognized or because JavaScript is disabled).

**Comment by sickill** [comment]
It's not supported now, but I like the idea.

`<img>` tag supports inline src like this:

```html
<img src="data:image/jpeg;base64,<base64-encoded-image-file-content>" />
```

It should be pretty easy to implement it in similar way, to make the following data URI working:

```html
<asciinema-player src="data:application/x-asciicast;base64,<base64-encoded-asciicast-file-content>"></asciinema-player>
```

**Comment by jameshfisher** [comment]
@sickill that would be perfect. I'd then be able to write something like

```bash
alias rec='asciinema rec - | base64 | cat <(printf "<asciinema-player src=\"data:application/x-asciicast;base64,") - <(printf "></asciinema-player>") | pbcopy'
```

So that I can do: `rec`, do terminal example, `Ctrl-D`, paste directly into blog post.

**Comment by sickill** [comment]
@jameshfisher ha, that's pretty neat alias! I'll try to look at this over the weekend (the famous last words 😛 )

**Comment by moritzdietz** [comment]
I just stumbled across this and was wondering if there are still plans on implementing that idea?

**Comment by inakianduaga** [comment]
BTW, this works

```
<asciinema-player src="data:text/plain;base64, <BASE64HERE> />
```

so content can definitely be inline, which is great for single file `revealJS` presentations

**Comment by moritzdietz** [comment]
Ah yeah great, it indeed works like you said. In your code example you are missing the closing  `"` though.
So it should be:
`<asciinema-player src="data:text/plain;base64, <BASE64HERE>"/>`
Thanks for sharing! :)

**Comment by ClouDevops101** [comment]
Nicely done guys, il like the idea

**Comment by sickill** [comment]
I've now added an example of using Data URL to the README: https://github.com/asciinema/asciinema-player#api
