### ISSUE TITLE
Server should return detailed error messages on failed upload

### ISSUE THREAD

**Issue by jtreminio** [asciinema/asciinema-player#9]
Attempting to upload a file with broken JSON returns a 400 error code:

    {
      "version": 1,
      "width": 106,
      "height": 25,
      "duration": 117.074547,
      "command": "/bin/bash",
      "title": "PuPHPet Sample",
      "env": {
        "TERM": "xterm-256color",
        "SHELL": "/bin/bash"
      },
      "stdout": [
        [
          0,
          "\u001b[?1034h\r\r\n\u001b[1m\u001b[30m[\u001b[34m12:30 PM\u001b[30m]-[\u001b[32mjtreminio\u001b[33m@\u001b[32mmacbook\u001b[30m]-[\u001b[35m~/www/puphpet/temp/puphpet-archive\u001b[30m]\u001b[0;33m \u001b[00m\u001b(B\u001b[m\r\r\n\u001b(B\u001b[m$ "
        ],
        [
          2.5,
          ""
        ],
      ]
    }

(Trailing comma error).

    [09:56 AM]-[jtreminio@macbook]-[~/www/puphpet/temp]
    $ asciinema upload asciinema.json
    Error: HTTP status: 400 Bad Request

Would it be better to return a message saying "File contains broken JSON"?

The file was hand-edited to remove messages, which is where the error came from.

**Comment by sickill** [comment]
I added a slightly better error message here: https://github.com/asciinema/asciinema/commit/ec6d8934
It displays a reason now. It will be in the next released version.
