### ISSUE TITLE
Issues integrating audio

### ISSUE THREAD

**Issue by carlsmith** [asciinema/asciinema-player#96]
Asciinema is awesome. Thank you.

## Background

I've been working on a website that uses Asciinema casts with voice, a bit like caTTY, but without the dependencies and complexity. This version just takes a JSON file that contains a bit of meta, including URLs for the cast file and the MP3 file.

The app combines everything in the browser, so you can record the cast and audio at the same time, or record the cast and play it back in your terminal (with maximum idle times or at a different speed) and record a voice over.

Note: The *cast's* playback speed is set to its duration divided by the audio duration (so they are always exactly the same length, and the *audio* never changes speed).

I was hoping to set callbacks on the Asciinema Player to control the audio player ([AmplitudeJS][1]), and was actually able to do this with Play and Pause events, but there's no way to hook into events on the Player's progress bar.

## What didn't work

Adding an event listener to the `span.progress-bar` element that handles `click` events almost worked, but the events do not always fire (which was super confusing). Clicking the progress bar nearly always fires the event, and from there, it's easy to get the duration and current time and update the audio player accordingly. Except, once in a while, the event just does not fire (this is in FireFox).

Note: Binding the listener to the container DIV for the controls, or even the entire player element, has the same effect: It will intermittently fail to fire click events. It's a really odd issue, and I couldn't find a pattern to it. Any ideas??

Note: The Asciinema Player still works correctly. It always registers clicks on the progress bar (updating the progress accordingly). It just doesn't provide a documented way to hook into those clicks, and trying to do it with event listeners is unreliable (at least on FireFox).

## What did work

I was able to work around it by setting the whole of the Player's control panel to `display: none` and reimplementing my own controls from scratch (the Asciinema Player's `play` and `pause` methods, and `currentTime` property made it easy to plumb in new (reliable) controls), but this is far from ideal. I quite like your controls, and they already work almost perfectly.

Note: If there was a new event (something like `onseek`) that fired whenever the progress bar was clicked (but not when it just updates as it fills up normally), that would be enough to use your controls directly (as we can already get the duration and current time).

[1]: https://521dimensions.com/open-source/amplitudejs

**Comment by carlsmith** [comment]
Just to be clear, my aim is not to compete with Asciinema. I teach Python and Web development, and want to use Asciinema, but need audio support. I'm happy to host my own solution, but would rather find a way for the Asciinema Player to *optionally* support audio, without complicating or greatly expanding the size of anything for those that just want the core functionality still.

**Comment by JavaCS3** [comment]
@carlsmith I'm also looking into how to add audio recording in asciinema. I did some experiment, my version audio/video is not synced.

**Comment by sickill** [comment]
Check out this other issue for examples of integrating audio in the latest version of the player: https://github.com/asciinema/asciinema-player/issues/159#issuecomment-1083547898
