### ISSUE TITLE
registerElement is deprecated in chome

### ISSUE THREAD

**Issue by RandomReaper** [asciinema/asciinema-player#98]
Chrome does this warning when using asciinema-player:

```
asciinema-player.js:308 [Deprecation] document.registerElement is deprecated and will be removed in M73, around March 2019. Please use window.customElements.define instead. See https://www.chromestatus.com/features/4642138092470272 for more details.
registerAsciinemaPlayerElement @ asciinema-player.js:308
(anonymous) @ asciinema-player.js:1209
(anonymous) @ asciinema-player.js:1210
main.js:60 Uncaught TypeError: Cannot read property 'addEventListener' of null
    at main.js:60
(anonymous) @ main.js:60
```
March 2019 seems not too far away, I think this issue should be handled.

**Comment by sickill** [comment]
Thanks for bringing this up @RandomReaper ! 👌

**Comment by sestegra** [comment]
@sickill Do you have an update about this issue ?
I've tried to fix it, but it's over my knowledge in JS.
Thanks in advance.

**Comment by sickill** [comment]
The player comes with polyfill for `document.registerElement`, so when Chrome removes it will still work (according to what is written on Polymer blog: https://www.polymer-project.org/blog/2018-10-02-webcomponents-v0-deprecations). So it's not super urgent issue.

Having said that, we should look into upgrading to new standard for custom elements (`customElements.define`).

**Comment by sestegra** [comment]
The only polyfill that I found in this project is `vt/resources/codepoint-polyfill.js` that is not coming from polymer project.

Are you sure it will work without issue ?

**Comment by sickill** [comment]
There's one at resources/public/Custom Element.min.js

**Comment by mxschmitt** [comment]
I've checked it with Chrome Canary (81) and yes it's still working.

**Comment by sickill** [comment]
Excellent @mxschmitt, thanks for checking! 👌

**Comment by sickill** [comment]
This is no longer an issue in the latest version of the player (3.0) since it doesn't use `registerElement` anymore.
